//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultationDiagnostic
    {
        public int ConsultationDiagnosticID { get; set; }
        public int DiagnosticID { get; set; }
        public int DiagnosticTypeID { get; set; }
        public bool Primal { get; set; }
        public int MedicalConsultationID { get; set; }
    
        public virtual Diagnostic Diagnostic { get; set; }
        public virtual DiagnosticType DiagnosticType { get; set; }
        public virtual MedicalConsultation MedicalConsultation { get; set; }
    }
}
