//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spConsultarValorPlanRest_Result
    {
        public Nullable<int> pla_cantidad { get; set; }
        public Nullable<int> iva { get; set; }
        public Nullable<double> valorplan { get; set; }
        public Nullable<double> valorinscripcion { get; set; }
        public string nombre { get; set; }
        public int codigo { get; set; }
        public string Beneficios { get; set; }
    }
}
