//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spInformeLogPelSONDA_Result
    {
        public string Tipo { get; set; }
        public string Servicio { get; set; }
        public int cdgimnasio { get; set; }
        public string Gimnasio { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
    }
}
