//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_preguntas
    {
        public int preg_codigo { get; set; }
        public string preg_descripcion { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<int> int_fkcodigo_contrato { get; set; }
        public string bits_replica { get; set; }
        public Nullable<int> pre_modificado { get; set; }
    }
}
