//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spClientesMigracionWeb_Result
    {
        public string Documento { get; set; }
        public string Identificacion_del_cliente { get; set; }
        public string Nombre_del_cliente { get; set; }
        public string Numero_de_telefono { get; set; }
        public string Numero_de_celular { get; set; }
        public string Barrio { get; set; }
        public string Sexo { get; set; }
        public string Dia_Mes { get; set; }
        public string Fecha_de_nacimiento { get; set; }
        public string Direccion { get; set; }
        public string Fecha_de_ingreso { get; set; }
        public string Como_supo { get; set; }
        public string Correo { get; set; }
        public string Universidad { get; set; }
        public string Eps { get; set; }
        public string Profesion { get; set; }
        public string Grupo { get; set; }
        public string Subgrupo { get; set; }
        public string Hobbie { get; set; }
        public string Nivel_de_ingreso { get; set; }
        public string Sucursal { get; set; }
        public string Nit_empresa { get; set; }
        public double Referido { get; set; }
        public string Comercial { get; set; }
        public Nullable<int> Codigo_plan { get; set; }
        public int Locker { get; set; }
        public string Grupo_familiar { get; set; }
        public string Autoriza_email { get; set; }
        public string Autoriza_SMS { get; set; }
        public string Autoriza_envio_de_informacion { get; set; }
        public string Autoriza_el_uso_de_huella { get; set; }
        public string Codigo_tarjeta { get; set; }
        public int Replicado_a_TG { get; set; }
    }
}
