//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spRIP_Result
    {
        public string typeID { get; set; }
        public string ID { get; set; }
        public string healthAdministratorEntityCode { get; set; }
        public int userType { get; set; }
        public string firstLastName { get; set; }
        public string secondLastName { get; set; }
        public string firstName { get; set; }
        public string secondName { get; set; }
        public Nullable<int> age { get; set; }
        public string unitMeasureAge { get; set; }
        public string gender { get; set; }
        public string departmentCodeHabitualResidence { get; set; }
        public string cityCodeHabitualResidence { get; set; }
        public string areaHabitualResidence { get; set; }
    }
}
