//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spFacturaModulo_Result
    {
        public int NUMERO_FACTURA { get; set; }
        public int COD_PLAN { get; set; }
        public string PRODUCTO { get; set; }
        public string DOCUMENTO { get; set; }
        public string CLIENTE { get; set; }
        public int cdgimnasio { get; set; }
        public string FECHA_COMPRA { get; set; }
        public string FECHA_VENCIMIENTO { get; set; }
        public string FECHA_INICIO { get; set; }
        public double VALOR { get; set; }
        public double IVA { get; set; }
        public double TOTAL { get; set; }
        public string PLAN_PERTENECE_A { get; set; }
        public string VENDIDO_EN { get; set; }
        public string EMPLEADO { get; set; }
        public string COMERCIAL { get; set; }
        public string IDCOMERCIAL { get; set; }
        public int DIAN { get; set; }
        public string ANULADO { get; set; }
        public string PREFIJO { get; set; }
        public string ESTABLECIMIENTO { get; set; }
        public string FACTURERO { get; set; }
        public int plusu_fkdia_codigo { get; set; }
        public int plusu_sucursal { get; set; }
    }
}
