//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spPrintClinicHistory_Result
    {
        public int consultationID { get; set; }
        public string printDate { get; set; }
        public string professionalName { get; set; }
        public string professionalID { get; set; }
        public string speciality { get; set; }
        public string businessName { get; set; }
        public string NIT { get; set; }
        public string branchName { get; set; }
        public Nullable<int> numberAppointment { get; set; }
        public string dateTimeAttention { get; set; }
        public string clientID { get; set; }
        public string clientName { get; set; }
        public string gender { get; set; }
        public string birthDate { get; set; }
        public Nullable<int> age { get; set; }
        public string area { get; set; }
        public string city { get; set; }
        public string departament { get; set; }
        public string consultationType { get; set; }
        public string consultationPurpose { get; set; }
        public string externalCause { get; set; }
        public string currentDiseaseComplementaryExam { get; set; }
        public string examResult { get; set; }
        public string observationsDiagnosticDiseases { get; set; }
        public string recommendationsDiagnosticDiseases { get; set; }
        public string numberSession { get; set; }
        public string valorationDiagnostic { get; set; }
        public string evolution { get; set; }
        public string positiveInjury { get; set; }
        public string daysOfWeek { get; set; }
        public string dailyTime { get; set; }
        public string range { get; set; }
        public string suitable { get; set; }
        public string positiveSession { get; set; }
        public string trainingHour { get; set; }
        public string referredTo { get; set; }
        public string nextAppointmentDays { get; set; }
        public string patientType { get; set; }
        public Nullable<double> actualWeight { get; set; }
        public string actualHeight { get; set; }
        public Nullable<double> goalFatPercentage { get; set; }
        public string goalWeeklyTrainingDays { get; set; }
        public string goalWeeklyTrainingMinutes { get; set; }
        public Nullable<double> weightGoal { get; set; }
        public string heartRate { get; set; }
        public Nullable<double> diastolicBloodPressure { get; set; }
        public Nullable<double> systolicBloodPressure { get; set; }
        public Nullable<double> temperature { get; set; }
        public Nullable<double> meanArterialPressure { get; set; }
        public string classificationAHA { get; set; }
        public Nullable<double> doubleProduct { get; set; }
        public Nullable<double> subscapularFold { get; set; }
        public Nullable<double> tricipitalFold { get; set; }
        public Nullable<double> axillaryFold { get; set; }
        public Nullable<double> bicipitalFold { get; set; }
        public Nullable<double> breastFold { get; set; }
        public Nullable<double> abdomenFold { get; set; }
        public Nullable<double> suprailiacFold { get; set; }
        public Nullable<double> middleSuprailiacFold { get; set; }
        public Nullable<double> lateralSuprailiacFold { get; set; }
        public Nullable<double> supraspinalFold { get; set; }
        public Nullable<double> ileocrestalFold { get; set; }
        public Nullable<double> thighFold { get; set; }
        public Nullable<double> legFold { get; set; }
        public Nullable<double> perimeterRelaxedArm { get; set; }
        public Nullable<double> perimeterTenseArm { get; set; }
        public Nullable<double> toraxPerimeter { get; set; }
        public Nullable<double> abdomenPerimeter { get; set; }
        public Nullable<double> waistPerimeter { get; set; }
        public Nullable<double> hipPerimeter { get; set; }
        public Nullable<double> perimeterUpperThigh { get; set; }
        public Nullable<double> middleThighPerimeter { get; set; }
        public Nullable<double> legPerimeter { get; set; }
        public Nullable<double> faulkner { get; set; }
        public Nullable<double> adiposityIndex { get; set; }
        public Nullable<double> fatPercentageDurninAndWomersley { get; set; }
        public Nullable<double> bodyDensityDurninAndWomersley { get; set; }
        public Nullable<double> yuhasz { get; set; }
        public Nullable<double> fattyWeightYuhasz { get; set; }
        public Nullable<double> magroWeightYuhasz { get; set; }
        public Nullable<double> fatPercentageYuhasz { get; set; }
        public Nullable<double> fatPercentageJacksonAndPollock { get; set; }
        public Nullable<double> bodyDensityJacksonAndPollock { get; set; }
        public Nullable<double> proportionalWeight { get; set; }
        public Nullable<double> muscleMassPercentage { get; set; }
        public Nullable<double> hipWaistRelationship { get; set; }
        public Nullable<double> IMC { get; set; }
        public Nullable<double> visceralFatPercentage { get; set; }
        public Nullable<double> KBasalCalories { get; set; }
        public Nullable<double> totalScoreBackRisk { get; set; }
        public string recommendationBackRisk { get; set; }
        public Nullable<double> totalScoreLowerRisk { get; set; }
        public string recommendationLowerRisk { get; set; }
        public Nullable<double> totalScoreHighRisk { get; set; }
        public string recommendationHighRisk { get; set; }
        public string somatotype { get; set; }
        public string testAdams { get; set; }
        public string testAdamsObservation { get; set; }
        public string abdominalStrength { get; set; }
        public string abdominalStrengthObservation { get; set; }
        public string coreRating { get; set; }
        public string coreRatingObservation { get; set; }
        public string basicSquat { get; set; }
        public string basicSquatObservation { get; set; }
        public string deepSquat { get; set; }
        public string deepSquatObservation { get; set; }
        public string recommendationEvaluationBySystem { get; set; }
        public string smoker { get; set; }
        public string smokerFrequency { get; set; }
        public string drinker { get; set; }
        public string frequencyDrinker { get; set; }
        public string nonPreferredFoods { get; set; }
        public string wakeUp { get; set; }
        public string sleep { get; set; }
        public string favoriteFood { get; set; }
        public string hours { get; set; }
        public string occupation { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public string cellPhone { get; set; }
        public string companionName { get; set; }
        public string companionTel { get; set; }
        public string contactName { get; set; }
        public string contactPhone { get; set; }
        public string contactRelationship { get; set; }
        public string eps { get; set; }
        public string consultationPurposeObservation { get; set; }
        public Nullable<int> TrainingFrequencyAssistance { get; set; }
        public Nullable<int> TrainingFrequencyTime { get; set; }
        public string AdditionalTrainingActivitiesCardio { get; set; }
        public string AdditionalTrainingActivitiesWeight { get; set; }
        public string AdditionalTrainingActivitiesGroupClasses { get; set; }
        public string AdditionalTrainingActivitiesOther { get; set; }
        public string Sedentary { get; set; }
        public string BecauseSedentary { get; set; }
        public string BoneStructureDescription { get; set; }
        public string BoneStructureObservation { get; set; }
        public string FeelPain { get; set; }
        public string FeelPainConstant { get; set; }
        public string PainLocation { get; set; }
        public string ObservationOther { get; set; }
    }
}
