//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spRptRptcuadrecaja_Result
    {
        public int FACTURA_INICIO { get; set; }
        public int FACTURA_FINAL { get; set; }
        public double TOTAL_CREDTIOS { get; set; }
        public Nullable<int> TOTAL_FACTURA { get; set; }
        public Nullable<double> TOTAL_VALOR { get; set; }
        public Nullable<double> TOTAL_DESCUENTO { get; set; }
        public string SUCURSAL { get; set; }
        public int CODSUCURSAL { get; set; }
        public Nullable<double> VALOR_BRUTO { get; set; }
        public Nullable<double> TOTAL_IVA { get; set; }
    }
}
