//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientesActivos
    {
        public int intCdGimnasio { get; set; }
        public int intSucursal { get; set; }
        public int intAno { get; set; }
        public bool bitPresupuesto { get; set; }
        public int intEnero { get; set; }
        public int intFebrero { get; set; }
        public int intMarzo { get; set; }
        public int intAbril { get; set; }
        public int intMayo { get; set; }
        public int intJunio { get; set; }
        public int intJulio { get; set; }
        public int intAgosto { get; set; }
        public int intSeptiembre { get; set; }
        public int intOctubre { get; set; }
        public int intNoviembre { get; set; }
        public int intDiciembre { get; set; }
    }
}
