//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spProfilesAllowCourtesies_Result
    {
        public int Id { get; set; }
        public int GYMID { get; set; }
        public int PlanID { get; set; }
        public int RolId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
