//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spRptHistoricClientsByPlan_Result
    {
        public double plusu_numero_fact { get; set; }
        public Nullable<System.DateTime> plusu_fecha_compra { get; set; }
        public string plusu_identifi_cliente { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> plusu_fecha_vcto { get; set; }
        public Nullable<System.DateTime> plusu_fecha_inicio { get; set; }
        public string pla_descripc { get; set; }
        public Nullable<System.DateTime> plusu_fecha_anulada { get; set; }
        public string pla_tipo { get; set; }
        public string plusu_est_anulada { get; set; }
        public string TipoFactura { get; set; }
        public int plusu_sucursal { get; set; }
        public string Sucursal { get; set; }
        public string strClasificacionPlan { get; set; }
        public Nullable<int> plusu_codigo_plan { get; set; }
    }
}
