//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_planes_adicionales
    {
        public int pla_num_pla_adi { get; set; }
        public int pla_codigo_plan { get; set; }
        public Nullable<int> pla_desde_hora_adicional { get; set; }
        public Nullable<int> pla_hasta_hora_adicional { get; set; }
        public Nullable<bool> pla_domingo_adicional { get; set; }
        public Nullable<bool> pla_lunes_adicional { get; set; }
        public Nullable<bool> pla_martes_adicional { get; set; }
        public Nullable<bool> pla_miercoles_adicional { get; set; }
        public Nullable<bool> pla_jueves_adicional { get; set; }
        public Nullable<bool> pla_viernes_adicional { get; set; }
        public Nullable<bool> pla_sabado_adicional { get; set; }
        public Nullable<bool> pla_festivo_adicional { get; set; }
        public Nullable<int> pla_min_desde_adicional { get; set; }
        public Nullable<int> pla_min_hasta_adicional { get; set; }
        public int pla_modificado { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public string bits_replica { get; set; }
    }
}
