//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_Campanas_Det
    {
        public int intID { get; set; }
        public string fk_CodigoPromocional { get; set; }
        public Nullable<double> PorcentajeDescuento { get; set; }
        public Nullable<double> valorDescuento { get; set; }
        public string idPlan { get; set; }
        public int cdgimnasio { get; set; }
    }
}
