//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDebitAccount
    {
        public int BankDebitAccountID { get; set; }
        public int BankID { get; set; }
        public int cdgimnasio { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string UserCreation { get; set; }
        public string BankCode { get; set; }
    }
}
