//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_grupoFamiliar_Maestro
    {
        public int gim_gf_pk_IDgrupo { get; set; }
        public Nullable<bool> gim_gf_bitControlIngreso { get; set; }
        public Nullable<int> gim_gf_intNumlIngresos { get; set; }
        public Nullable<System.DateTime> gim_gf_fechamodificado { get; set; }
        public Nullable<int> gim_modificado { get; set; }
        public int intId { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public string bits_replica { get; set; }
        public Nullable<int> cdgimnasio { get; set; }
    }
}
