//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_sub_tipo_gasto
    {
        public int subtg_codigo { get; set; }
        public string subtg_descripcion { get; set; }
        public Nullable<int> subtg_tg_codigo { get; set; }
        public int cdgimnasio { get; set; }
        public string subtg_tipo_gasto { get; set; }
        public Nullable<bool> subtg_exg_proveedor { get; set; }
    }
}
