//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblversionBD_
    {
        public short intID { get; set; }
        public string strBDVersion { get; set; }
        public string strDescripcionVersion { get; set; }
        public System.DateTime dtmFechaVersion { get; set; }
        public string strAutor { get; set; }
        public string strVersionAPP { get; set; }
    }
}
