//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogAdminFeeConfig
    {
        public int lafc_intId { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<int> afc_intId { get; set; }
        public Nullable<int> per_intId { get; set; }
        public Nullable<int> afc_intPeriodsNumber { get; set; }
        public string afc_strDescription { get; set; }
        public Nullable<bool> afc_bitExpirationPeriod { get; set; }
        public Nullable<bool> afc_bitState { get; set; }
        public string afc_strModifiedUser { get; set; }
        public Nullable<System.DateTime> afc_dtmModifiedDate { get; set; }
        public Nullable<System.DateTime> afc_dtmDateApply { get; set; }
        public string PeriodDetailBuyLog { get; set; }
        public string AdditionalCashingLog { get; set; }
        public Nullable<bool> lafc_bitModified { get; set; }
        public string bits_replica { get; set; }
    }
}
