//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spConsultaFactCortClientePlan_Result
    {
        public string tipo { get; set; }
        public string cli_identifi { get; set; }
        public Nullable<System.DateTime> plusu_fecha_vcto { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<int> plusu_codigo_plan { get; set; }
    }
}
