//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spSuscripcionesMP_Result
    {
        public string cli_identifi { get; set; }
        public string name { get; set; }
        public string clientAddress { get; set; }
        public string phone { get; set; }
        public int suc_intpkIdentificacion { get; set; }
        public string suc_strNombre { get; set; }
        public int pla_codigo { get; set; }
        public string planName { get; set; }
        public string cardNumber { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string methodType { get; set; }
        public string AccountType { get; set; }
        public string registrationState { get; set; }
        public string ActiveState { get; set; }
        public int retry { get; set; }
        public string lastRetry { get; set; }
        public string nextPay { get; set; }
        public bool debitState { get; set; }
        public Nullable<bool> Active { get; set; }
        public int DebitAccountID { get; set; }
    }
}
