//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_planes_usuario_especiales_Detalle
    {
        public int id { get; set; }
        public int cdgimnasio { get; set; }
        public int Codigo_producto { get; set; }
        public string Tipo_producto { get; set; }
        public int Numero_Cortesia_Abonado { get; set; }
        public int intSucursal { get; set; }
        public int intCodigo_DIAN { get; set; }
        public Nullable<double> ValorUnitario { get; set; }
        public Nullable<int> cantidad_venta { get; set; }
        public int porcentajeIva { get; set; }
        public double Subtotal { get; set; }
        public int porcentajeDescuento { get; set; }
        public double Total_Descuento { get; set; }
        public Nullable<double> Iva_Venta { get; set; }
        public double Total { get; set; }
        public string bits_replica { get; set; }
    }
}
