//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTypes
    {
        public int id { get; set; }
        public string account_type_description { get; set; }
        public int cdgimnasio { get; set; }
        public System.DateTime creation_date { get; set; }
        public string creation_user { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_user { get; set; }
    
        public virtual Gym_Account_Types Gym_Account_Types { get; set; }
        public virtual gim_gimnasio gim_gimnasio { get; set; }
    }
}
