//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDebitAccountrespaldo
    {
        public int AccountDebitAccountID { get; set; }
        public string ClientID { get; set; }
        public string HolderID { get; set; }
        public string HolderName { get; set; }
        public int BankID { get; set; }
        public int AccountType { get; set; }
        public string AccountNumber { get; set; }
        public string State { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string User { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> DateModify { get; set; }
        public string UserModify { get; set; }
        public int cdgimnasio { get; set; }
        public string Reference { get; set; }
        public Nullable<int> holderIdType { get; set; }
    }
}
