//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLogPushNotifications
    {
        public int id { get; set; }
        public Nullable<int> cdgimnasio { get; set; }
        public string tokenClient { get; set; }
        public string topic { get; set; }
        public string identifyClient { get; set; }
        public string state { get; set; }
    }
}
