//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallefacturasresolucion8mma
    {
        public int det_numero { get; set; }
        public int det_factura { get; set; }
        public Nullable<int> det_codigo_pago { get; set; }
        public Nullable<double> det_valor_pago { get; set; }
        public string det_numero_documento { get; set; }
        public string det_numero_documento_uno { get; set; }
        public int det_sucursal { get; set; }
        public int det_modificado { get; set; }
        public Nullable<int> det_sede { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public string det_comprobante_fp { get; set; }
        public int det_fkdia_codigo { get; set; }
        public string bits_replica { get; set; }
        public Nullable<int> dataphoneProviderId { get; set; }
    }
}
