//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FA_LogErrores
    {
        public int log_intId { get; set; }
        public Nullable<System.DateTime> log_dtmDateLog { get; set; }
        public string log_strError { get; set; }
        public Nullable<int> cdgimnasio { get; set; }
        public string servicio { get; set; }
    }
}
