//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_feedingPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gim_feedingPlan()
        {
            this.gim_dietDay = new HashSet<gim_dietDay>();
            this.gim_nutritionRecomendationDetail = new HashSet<gim_nutritionRecomendationDetail>();
            this.gim_objetivesFeedingPlanDetail = new HashSet<gim_objetivesFeedingPlanDetail>();
        }
    
        public int PK_feedingPlanId { get; set; }
        public int cdgimnasio { get; set; }
        public int FK_nutritionGuideId { get; set; }
        public string Description { get; set; }
        public bool bitPerDay { get; set; }
        public bool bitPerFoods { get; set; }
        public string client_identifi { get; set; }
        public string user_identifi { get; set; }
        public string user_name { get; set; }
        public Nullable<int> especiality_id { get; set; }
        public string especiality_name { get; set; }
        public int branch_id { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public string weight { get; set; }
        public string goalWeight { get; set; }
        public string IMC { get; set; }
        public string fatDurnin { get; set; }
        public string fatYuhasz { get; set; }
        public string fatJackson { get; set; }
        public string fat { get; set; }
        public string goalFat { get; set; }
        public string historicalHTML { get; set; }
        public string nutritionalGuide { get; set; }
        public Nullable<int> MedicalConsultationID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gim_dietDay> gim_dietDay { get; set; }
        public virtual gim_nutritionGuide gim_nutritionGuide { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gim_nutritionRecomendationDetail> gim_nutritionRecomendationDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gim_objetivesFeedingPlanDetail> gim_objetivesFeedingPlanDetail { get; set; }
    }
}
