//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_creditos
    {
        public int cre_numero { get; set; }
        public Nullable<double> cre_identifi { get; set; }
        public Nullable<int> cre_factura { get; set; }
        public Nullable<System.DateTime> cre_fecha { get; set; }
        public Nullable<System.DateTime> cre_fecharealpago { get; set; }
        public Nullable<double> cre_valor { get; set; }
        public Nullable<double> cre_valor_abono { get; set; }
        public bool cre_pagado { get; set; }
        public bool cre_anulado { get; set; }
        public int cre_sucursal { get; set; }
        public int cre_modificado { get; set; }
        public Nullable<int> cre_sede { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public string bits_replica { get; set; }
        public int cre_fkdia_codigo { get; set; }
        public Nullable<bool> cre_bitIsRegistration { get; set; }
    }
}
