//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_clientes_especiales
    {
        public double cli_identifi { get; set; }
        public Nullable<int> cli_tipo_identifi { get; set; }
        public string cli_nombres { get; set; }
        public string cli_primer_apellido { get; set; }
        public string cli_segundo_apellido { get; set; }
        public Nullable<System.DateTime> cli_fecha_ingreso { get; set; }
        public string cli_telefono { get; set; }
        public string cli_direccion { get; set; }
        public string cli_email { get; set; }
        public bool cli_cortesia { get; set; }
        public bool cli_entrar_conocer { get; set; }
        public bool cli_entro_cortesia { get; set; }
        public Nullable<System.DateTime> cli_fecha_entrada_cortesia { get; set; }
        public string cli_como_supo { get; set; }
        public int cli_modificado { get; set; }
        public Nullable<int> cli_sede { get; set; }
        public Nullable<int> cli_intfkSucursal { get; set; }
        public byte[] cli_foto { get; set; }
        public Nullable<bool> cli_bitEsInvitado { get; set; }
        public Nullable<double> cli_strIdInvita { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public string bits_replica { get; set; }
        public int cdgimnasio { get; set; }
        public string cli_comercial { get; set; }
        public Nullable<bool> cli_envioemail { get; set; }
        public Nullable<bool> cli_envioSMS { get; set; }
        public Nullable<System.DateTime> cli_dtmDateBorn { get; set; }
        public Nullable<int> cli_Genre { get; set; }
        public int Id { get; set; }
        public Nullable<int> cli_intEPS { get; set; }
        public string cli_CreatedUser { get; set; }
        public Nullable<System.DateTime> cli_ModifiedDate { get; set; }
        public string cli_ModifiedUser { get; set; }
        public Nullable<bool> cli_EntryFingerprint { get; set; }
        public Nullable<bool> bitCarnetdevacunaciondeCOVID19 { get; set; }
        public byte[] IMGCarnetdevacunaciondeCOVID19 { get; set; }
        public Nullable<int> cli_intPais { get; set; }
    }
}
