//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_con_fac
    {
        public int con_con_fac { get; set; }
        public Nullable<int> num_fac_con { get; set; }
        public Nullable<System.DateTime> fec_ini_con { get; set; }
        public Nullable<System.DateTime> fec_ter_con { get; set; }
        public bool des_con { get; set; }
        public string desc_mot_cong { get; set; }
        public int con_sucursal { get; set; }
        public int con_modificado { get; set; }
        public Nullable<int> con_sede { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public int con_fkdia_codigo { get; set; }
        public string bits_replica { get; set; }
    }
}
