//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_MaestroInterfacesContables
    {
        public int MaestroInterfacesContablesID { get; set; }
        public string CodigoInterfacesContable { get; set; }
        public string Parametro { get; set; }
        public string ValorParametro { get; set; }
        public int cdgimnasio { get; set; }
    }
}
