//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_horarios_clase
    {
        public int cdhorario_clase { get; set; }
        public int cdclase { get; set; }
        public System.DateTime hora { get; set; }
        public System.DateTime hora_fin { get; set; }
        public string dia { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string profesor { get; set; }
        public string estado { get; set; }
        public int cupo { get; set; }
        public int hor_modificado { get; set; }
        public Nullable<int> sede { get; set; }
        public Nullable<int> salon { get; set; }
        public string clase_dia_hora { get; set; }
        public int cdgimnasio { get; set; }
        public string bits_replica { get; set; }
    }
}
