//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_cambio_sucursal
    {
        public int id { get; set; }
        public int cdgimnasio { get; set; }
        public string identification { get; set; }
        public int previous_branch { get; set; }
        public int new_branch { get; set; }
        public int invoice { get; set; }
        public int dian { get; set; }
        public int branch { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string modified_user { get; set; }
    }
}
