//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_planes_sucursal_ingreso
    {
        public int sucing_intfkCodigoPlan { get; set; }
        public int sucing_intfkSucursalVender { get; set; }
        public int sucing_intfkSucursalEntrar { get; set; }
        public Nullable<int> sucing_modificado { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public string bits_replica { get; set; }
        public string Zonas { get; set; }
    }
}
