//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_cupo_horario
    {
        public int cdcupo_horario { get; set; }
        public int cdhorario_clase { get; set; }
        public int cupo { get; set; }
        public System.DateTime fecha_horario { get; set; }
        public int cup_modificado { get; set; }
    }
}
