//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_InterfacesContables
    {
        public int InterfacesContablesID { get; set; }
        public string Codigo { get; set; }
        public string NombreInterfaz { get; set; }
        public string NombreArchivo { get; set; }
        public string ExtensionArchivo { get; set; }
        public string DescripcionArchivo { get; set; }
    }
}
