//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_detalle_preguntas
    {
        public int detpreg_Fkpregunta { get; set; }
        public int detpreg_Fkdetallecontrato { get; set; }
        public bool detpreg_sino { get; set; }
        public bool bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<int> detpreg_modificado { get; set; }
        public int dtpreg_sucursalId { get; set; }
        public string bits_replica { get; set; }
    }
}
