//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_MvtoDebAutom
    {
        public string mvtoDA_identifi { get; set; }
        public System.DateTime mvtoDA_fecha { get; set; }
        public bool mvtoDA_aprobado { get; set; }
        public bool mvtoDA_procesado { get; set; }
        public string mvtoDA_descripcion { get; set; }
        public Nullable<int> mvtoDA_factura { get; set; }
        public Nullable<double> mvtoDA_valor { get; set; }
        public int mvtoDA_sucursal { get; set; }
        public int intId { get; set; }
        public int mvtoDA_modificado { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public string mvtoDA_referencia { get; set; }
        public int cdgimnasio { get; set; }
    }
}
