//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_FacturasPorCobrar_Servicio
    {
        public int Id { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<int> IDSucursal { get; set; }
        public string NombreSucursal { get; set; }
        public string NumeroFactura { get; set; }
        public string ResolucionDian { get; set; }
        public string NitEmpresa { get; set; }
        public string NombreEmpresa { get; set; }
        public string ValorFactura { get; set; }
        public string CorreoResponsable { get; set; }
        public Nullable<bool> bitEstado { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
