//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_clases_net
    {
        public string cla_codigo { get; set; }
        public Nullable<System.DateTime> cla_hora { get; set; }
        public Nullable<int> cla_cantidad_cupos { get; set; }
        public bool cla_modificado { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
    }
}
