//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_motivoscancel
    {
        public int motcancel_codigo { get; set; }
        public string motcancel_descripcion { get; set; }
        public Nullable<int> motcancel_modificado { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
    }
}
