//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_ModCom_Enc
    {
        public int intID { get; set; }
        public Nullable<int> intIDTipoActividad { get; set; }
        public string strDescripcion { get; set; }
        public Nullable<System.DateTime> dtmFecha { get; set; }
        public Nullable<int> intDuracion { get; set; }
        public Nullable<int> intAlerta { get; set; }
        public Nullable<int> intIDPlantilla { get; set; }
        public Nullable<int> intIDResponsable { get; set; }
        public int cdgimnasio { get; set; }
        public int intSucursal { get; set; }
        public Nullable<bool> bitEnProceso { get; set; }
        public Nullable<int> intPrioridad { get; set; }
        public Nullable<System.DateTime> dtmFechaCreacion { get; set; }
        public Nullable<int> tipo_categoria { get; set; }
    }
}
