//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_programa_comf
    {
        public int pro_codigo { get; set; }
        public string pro_descripcion { get; set; }
        public int pro_servicio { get; set; }
        public bool pro_modificado { get; set; }
        public int intId { get; set; }
        public int cdgimnasio { get; set; }
        public string bits_replica { get; set; }
        public string pro_strCodigoSirevac { get; set; }
    }
}
