//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_divisas
    {
        public int div_intId { get; set; }
        public string div_strDescripcion { get; set; }
        public string div_strSimbolo { get; set; }
        public string div_strCodigo { get; set; }
        public string div_icon { get; set; }
    }
}
