//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_listanegra
    {
        public double listneg_floatId { get; set; }
        public string listneg_strNombre { get; set; }
        public string listneg_strTelefono { get; set; }
        public string listneg_strDireccion { get; set; }
        public string listneg_strEmail { get; set; }
        public bool listneg_bitEstado { get; set; }
        public Nullable<int> listneg_modificado { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public string bits_replica { get; set; }
    }
}
