//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gim_usuarios()
        {
            this.Gym_User_Social_Network = new HashSet<Gym_User_Social_Network>();
        }
    
        public string usu_documento { get; set; }
        public string usu_usuario { get; set; }
        public string usu_contrasena { get; set; }
        public int usu_perfil { get; set; }
        public Nullable<int> usu_modificado { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string estado { get; set; }
        public string bits_replica { get; set; }
        public Nullable<bool> claveTemporal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gym_User_Social_Network> Gym_User_Social_Network { get; set; }
    }
}
