//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_usuarios_net
    {
        public int usu_id { get; set; }
        public string usu_documento { get; set; }
        public string usu_contrasena { get; set; }
        public int cdgimnasio { get; set; }
        public System.DateTime usu_fecha_cambio { get; set; }
        public string bits_replica { get; set; }
    }
}
