//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_envio_mail
    {
        public int send_mailId { get; set; }
        public System.DateTime fecha_envio { get; set; }
        public string tipo_envio { get; set; }
        public int cdgimnasio { get; set; }
        public string cdcliente { get; set; }
        public bool activo { get; set; }
    }
}
