//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_OtrosMaestros
    {
        public int otro_intIdOtros { get; set; }
        public string otro_strTablaMaestro { get; set; }
        public int otro_FKintCodigoMestro { get; set; }
        public string otro_FKstrIdentificacion { get; set; }
        public string otro_strDescipcion { get; set; }
        public int cdgimnasio { get; set; }
    }
}
