//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_menuDetailDiet
    {
        public int PK_menuDetailDietId { get; set; }
        public int cdgimnasio { get; set; }
        public int FK_menuId { get; set; }
        public int FK_feedingSessionDetailId { get; set; }
        public string Description { get; set; }
    
        public virtual gim_feedingSessionDetail gim_feedingSessionDetail { get; set; }
        public virtual gim_nutritionMenus gim_nutritionMenus { get; set; }
    }
}
