//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_metodos_formas_pago
    {
        public int mfp_fkintMetodoPago { get; set; }
        public int mfp_fkintPagCodigo { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<int> mfp_modificado { get; set; }
        public string bits_replica { get; set; }
    }
}
