//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_planes_usuario_especiales
    {
        public int cdplusuesp { get; set; }
        public int cdgimnasio { get; set; }
        public double plusu_numero_fact { get; set; }
        public Nullable<System.DateTime> plusu_fecha_compra { get; set; }
        public string plusu_identifi_cliente { get; set; }
        public Nullable<int> plusu_codigo_plan { get; set; }
        public Nullable<int> plusu_tiq_disponible { get; set; }
        public Nullable<System.DateTime> plusu_fecha_vcto { get; set; }
        public Nullable<int> plusu_descuento { get; set; }
        public Nullable<double> plusu_identifi_desc { get; set; }
        public string plusu_usuario { get; set; }
        public Nullable<bool> plusu_est_impreso { get; set; }
        public Nullable<bool> plusu_est_copia { get; set; }
        public Nullable<bool> plusu_est_anulada { get; set; }
        public string plusu_descripc_anulada { get; set; }
        public Nullable<System.DateTime> plusu_fecha_anulada { get; set; }
        public Nullable<double> plusu_usuario_anula { get; set; }
        public Nullable<bool> plusu_avisado { get; set; }
        public Nullable<double> plusu_valor { get; set; }
        public string plusu_forma_pago { get; set; }
        public Nullable<double> plusu_identifi_beca { get; set; }
        public int plusu_sucursal { get; set; }
        public Nullable<double> plusu_nueva_factura { get; set; }
        public Nullable<double> plusu_valor_iva { get; set; }
        public Nullable<System.DateTime> plusu_fecha_inicio { get; set; }
        public Nullable<int> plusu_cantidad { get; set; }
        public Nullable<int> plusu_dias_congelados { get; set; }
        public Nullable<int> plusu_motivo_descuento { get; set; }
        public Nullable<int> plusu_modificado { get; set; }
        public Nullable<int> plusu_sede { get; set; }
        public Nullable<double> plusu_numero_fact_titular { get; set; }
        public Nullable<int> plusu_intcantidadtotaltiquetes { get; set; }
        public Nullable<bool> plusu_bitEsConvenio { get; set; }
        public Nullable<bool> plusu_bitCambioPlan { get; set; }
        public Nullable<short> plusu_intturno { get; set; }
        public int plusu_intfkSucursalPlan { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public Nullable<int> plusu_puntosdisponibles { get; set; }
        public Nullable<int> plusu_com_numero { get; set; }
        public string plusu_empresasclientes { get; set; }
        public Nullable<bool> plusu_bitAbonado { get; set; }
        public Nullable<bool> plusu_bitBolsaDinero { get; set; }
        public Nullable<double> plusu_comercial { get; set; }
        public string plusu_strAutorizacion { get; set; }
        public Nullable<bool> plusu_bitregistroonline { get; set; }
        public Nullable<System.DateTime> plusu_fecha_autoriza { get; set; }
        public Nullable<double> plusu_emp_autoriza { get; set; }
        public Nullable<bool> plusu_bit_autoriza { get; set; }
        public Nullable<int> plusu_fkdia_codigo { get; set; }
        public string bits_replica { get; set; }
        public Nullable<bool> plusu_isWeb { get; set; }
        public string plusu_strAcudiente { get; set; }
        public Nullable<bool> plusu_bitFirstInvoiceTerm { get; set; }
        public Nullable<bool> plusu_bitUsedByMembership { get; set; }
        public Nullable<int> numero_Cambio { get; set; }
        public Nullable<bool> bitfechaini { get; set; }
        public Nullable<bool> bitfechaven { get; set; }
        public Nullable<int> TechnologicalSupplierID { get; set; }
        public Nullable<bool> isElectronicInvoicing { get; set; }
        public string DocumentID { get; set; }
        public string CUFE { get; set; }
        public Nullable<int> codPlanPaquete { get; set; }
        public Nullable<bool> bitGrupoFamiliar { get; set; }
        public Nullable<double> num_facturaPertenecia { get; set; }
        public Nullable<int> num_resolucionPertenecia { get; set; }
    }
}
