//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_menus
    {
        public int mnu_PKcodigo { get; set; }
        public string mnu_nombretecnico { get; set; }
        public string mnu_nombrevisible { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
    }
}
