//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_megas
    {
        public int intmeg_Fknumero_transaccion { get; set; }
        public int intmeg_puntos { get; set; }
        public string strmeg_tipotrasaccion { get; set; }
        public System.DateTime datmeg_fecha_compra { get; set; }
        public Nullable<bool> bitmeg_modificado { get; set; }
        public int intmeg_sucursal_transaccion { get; set; }
        public string intmeg_identifi_cliente { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public string bits_replica { get; set; }
    }
}
