//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_nutritionGuide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gim_nutritionGuide()
        {
            this.gim_feedingPlan = new HashSet<gim_feedingPlan>();
            this.gim_foodTypeDetail = new HashSet<gim_foodTypeDetail>();
        }
    
        public int PK_nutritionGuideId { get; set; }
        public int cdgimnasio { get; set; }
        public int FK_nutritionPatienTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gim_feedingPlan> gim_feedingPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gim_foodTypeDetail> gim_foodTypeDetail { get; set; }
        public virtual gim_nutritionPatientTypes gim_nutritionPatientTypes { get; set; }
    }
}
