//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_correo_config
    {
        public int corr_intpkCodigo { get; set; }
        public string corr_email { get; set; }
        public string corr_password { get; set; }
        public string corr_smtp { get; set; }
        public Nullable<bool> corr_cnnencriptada { get; set; }
        public Nullable<int> corr_puerto { get; set; }
        public bool corr_archivoHtml { get; set; }
        public string corr_strfkGimnasioNit { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
    }
}
