//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_biosecurityQuestionsDetail
    {
        public int PK_questionDetailId { get; set; }
        public int cdgimnasio { get; set; }
        public int FK_questionId { get; set; }
        public bool isClient { get; set; }
        public string identifi { get; set; }
        public Nullable<bool> answer { get; set; }
        public System.DateTime dateAnswer { get; set; }
        public bool read { get; set; }
        public bool answered { get; set; }
        public string planType { get; set; }
        public int branchId { get; set; }
        public string resolutionNumber { get; set; }
        public Nullable<int> invoiceNumber { get; set; }
        public string userName { get; set; }
        public string phone { get; set; }
        public string cellphone { get; set; }
        public string email { get; set; }
        public string receiptType { get; set; }
        public Nullable<int> surveyId { get; set; }
        public Nullable<int> dianId { get; set; }
    
        public virtual gim_biosecurityQuestions gim_biosecurityQuestions { get; set; }
    }
}
