//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_cliente_extra
    {
        public int cli_e_concecutivo { get; set; }
        public Nullable<int> cli_e_numero_fact { get; set; }
        public Nullable<double> cli_e_identifi { get; set; }
        public Nullable<int> cli_e_num_especial { get; set; }
        public int cli_e_sucursal { get; set; }
        public int cli_e_modificado { get; set; }
        public Nullable<int> cli_e_sede { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
    }
}
