//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_profesiones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gim_profesiones()
        {
            this.tblFechasEspecialesProfesion = new HashSet<tblFechasEspecialesProfesion>();
        }
    
        public short pro_codigo { get; set; }
        public string pro_descripc { get; set; }
        public Nullable<int> pro_modificado { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public string bits_replica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFechasEspecialesProfesion> tblFechasEspecialesProfesion { get; set; }
    }
}
