//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_clases
    {
        public int cdclase { get; set; }
        public int cdgimnasio { get; set; }
        public string nombre { get; set; }
        public Nullable<int> min_puntos { get; set; }
        public string intensidad_alta { get; set; }
        public string intensidad_media { get; set; }
        public string intensidad_baja { get; set; }
        public Nullable<int> porcentaje_cancelacion { get; set; }
        public Nullable<int> cupo_maximo { get; set; }
        public Nullable<int> tiempo_maximo_reserva { get; set; }
        public Nullable<int> horas_anticipa_reserva { get; set; }
        public int estado { get; set; }
        public Nullable<int> num_reservas { get; set; }
        public string slug { get; set; }
        public Nullable<int> tipo_clase { get; set; }
        public string url_imagen { get; set; }
        public Nullable<int> cla_modificado { get; set; }
        public Nullable<bool> prueba { get; set; }
        public Nullable<int> num_FilasPosiciones { get; set; }
        public Nullable<int> num_ColumnasPosiciones { get; set; }
        public Nullable<bool> requierePosicion { get; set; }
        public Nullable<int> cdsucursal { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public string bits_replica { get; set; }
        public Nullable<int> horas_anticipa_reserva_Finaliza { get; set; }
        public Nullable<int> intZona { get; set; }
        public Nullable<int> idMonitoresDeEntrenamiento { get; set; }
        public Nullable<int> intValor_Reserva_Cliente_SinPlan_o_Tiquetes { get; set; }
    }
}
