//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_contrato
    {
        public int cont_codigo { get; set; }
        public string cont_texto { get; set; }
        public byte[] cont_firma_responsable { get; set; }
        public bool cont_activar { get; set; }
        public bool cont_mostrar_contrato { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<int> cont_modificado { get; set; }
        public string bits_replica { get; set; }
        public Nullable<int> int_fkTipoContrato { get; set; }
    }
}
