//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_subgru_adicionales
    {
        public int subgru_adi_num_subgru_adi { get; set; }
        public int subgru_adi_codigo_subgru { get; set; }
        public Nullable<int> subgru_adi_desde_hora_adicional { get; set; }
        public Nullable<int> subgru_adi_hasta_hora_adicional { get; set; }
        public Nullable<bool> subgru_adi_domingo_adicional { get; set; }
        public Nullable<bool> subgru_adi_lunes_adicional { get; set; }
        public Nullable<bool> subgru_adi_martes_adicional { get; set; }
        public Nullable<bool> subgru_adi_miercoles_adicional { get; set; }
        public Nullable<bool> subgru_adi_jueves_adicional { get; set; }
        public Nullable<bool> subgru_adi_viernes_adicional { get; set; }
        public Nullable<bool> subgru_adi_sabado_adicional { get; set; }
        public Nullable<bool> subgru_adi_festivo_adicional { get; set; }
        public Nullable<int> subgru_adi_min_desde_adicional { get; set; }
        public Nullable<int> subgru_adi_min_hasta_adicional { get; set; }
        public int subgru_adi_modificado { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public string bits_replica { get; set; }
    }
}
