//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenesSucursal
    {
        public int imgSuc_intPKId { get; set; }
        public int cdgimnasio { get; set; }
        public int imgSuc_intFKIdSuc { get; set; }
        public string imgSuc_strNombreImg { get; set; }
        public bool imgSuc_bitPrincipal { get; set; }
        public Nullable<bool> stateImg { get; set; }
        public string imgSuc_strCreatedUser { get; set; }
        public Nullable<System.DateTime> imgSuc_dtmCreatedDate { get; set; }
        public string imgSuc_strModifiedUser { get; set; }
        public Nullable<System.DateTime> imgSuc_dtmModifiedDate { get; set; }
    }
}
