//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogFailedResponseTransaction
    {
        public int LogFailedResponseTransactionID { get; set; }
        public Nullable<int> PaymentGatewayID { get; set; }
        public string PaymentGatewayName { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string DataReceived { get; set; }
        public Nullable<int> cdgimnasio { get; set; }
        public string ClientID { get; set; }
        public Nullable<int> BranchID { get; set; }
    }
}
