//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPostWompi
    {
        public int logID { get; set; }
        public string statusW { get; set; }
        public string IdTranWompi { get; set; }
        public string Reference { get; set; }
        public int cdgimnasio { get; set; }
        public int SucursalID { get; set; }
        public string payment_method_type { get; set; }
        public System.DateTime FechaCreation { get; set; }
        public string sent_at { get; set; }
        public string identificacion { get; set; }
        public string NombreCliente { get; set; }
        public string JsonWompi { get; set; }
    }
}
