//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTransaction
    {
        public int LogTransactionID { get; set; }
        public string Transaction { get; set; }
        public System.DateTime DateTransaction { get; set; }
        public string Description { get; set; }
        public int cdgimnasio { get; set; }
        public string User { get; set; }
    }
}
