//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleMedicalModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleMedicalModule()
        {
            this.ConfigurationMedicalModule = new HashSet<ConfigurationMedicalModule>();
            this.CUP = new HashSet<CUP>();
            this.MedicalConsultation = new HashSet<MedicalConsultation>();
            this.MedicalConsultationDetailDoctor = new HashSet<MedicalConsultationDetailDoctor>();
            this.MedicalConsultationDetailEvaluator = new HashSet<MedicalConsultationDetailEvaluator>();
            this.MedicalConsultationDetailNutritionist = new HashSet<MedicalConsultationDetailNutritionist>();
            this.MedicalConsultationDetailPhysiotherapist = new HashSet<MedicalConsultationDetailPhysiotherapist>();
            this.SectionMedicalModule = new HashSet<SectionMedicalModule>();
        }
    
        public int ModuleID { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigurationMedicalModule> ConfigurationMedicalModule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUP> CUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalConsultation> MedicalConsultation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalConsultationDetailDoctor> MedicalConsultationDetailDoctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalConsultationDetailEvaluator> MedicalConsultationDetailEvaluator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalConsultationDetailNutritionist> MedicalConsultationDetailNutritionist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalConsultationDetailPhysiotherapist> MedicalConsultationDetailPhysiotherapist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectionMedicalModule> SectionMedicalModule { get; set; }
    }
}
