//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEL_AccountInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEL_AccountInfo()
        {
            this.PEL_Lote = new HashSet<PEL_Lote>();
        }
    
        public int aci_IdCuenta { get; set; }
        public string aci_strIdentificacion { get; set; }
        public int aci_intEstado { get; set; }
        public bool aci_bitActivo { get; set; }
        public string aci_strNumero { get; set; }
        public string aci_strTipo { get; set; }
        public string aci_intBanco { get; set; }
        public System.DateTime aci_Fecha { get; set; }
        public int aci_cdgimnasio { get; set; }
        public Nullable<bool> aci_seleccionada { get; set; }
        public string aci_FKidentifiCliente { get; set; }
        public string aci_Descripcion { get; set; }
        public Nullable<System.DateTime> aci_FechaNotificacion { get; set; }
        public string aci_canal { get; set; }
    
        public virtual TblEstado TblEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEL_Lote> PEL_Lote { get; set; }
    }
}
