//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEL_Lote
    {
        public int IdLote { get; set; }
        public int IdCuenta { get; set; }
        public string URL { get; set; }
        public int IdEstado { get; set; }
        public bool Activo { get; set; }
        public string cc_Identificador { get; set; }
        public string cc_LlaveTransaccional { get; set; }
        public string cc_LlaveMD5 { get; set; }
        public int cdgimnasio { get; set; }
        public string cc_checksum { get; set; }
        public string cc_Descripcion { get; set; }
        public Nullable<bool> Notificada { get; set; }
    
        public virtual PEL_AccountInfo PEL_AccountInfo { get; set; }
        public virtual TblEstado TblEstado { get; set; }
    }
}
