//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEL_PetitionLogs
    {
        public long PK_PetitionLogId { get; set; }
        public int paymentGatewayID { get; set; }
        public int gymId { get; set; }
        public System.DateTime date { get; set; }
        public string requestUrl { get; set; }
        public int requestId { get; set; }
        public string reference { get; set; }
        public string request { get; set; }
        public string response { get; set; }
    }
}
