//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionMedicalModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SectionMedicalModule()
        {
            this.ConfigurationMedicalModule = new HashSet<ConfigurationMedicalModule>();
            this.DependenceSection = new HashSet<DependenceSection>();
        }
    
        public int SectionID { get; set; }
        public string Name { get; set; }
        public int ModuleID { get; set; }
        public int Order { get; set; }
        public int Type { get; set; }
        public Nullable<int> RootID { get; set; }
        public Nullable<int> TypeFieldID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigurationMedicalModule> ConfigurationMedicalModule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DependenceSection> DependenceSection { get; set; }
        public virtual ModuleMedicalModule ModuleMedicalModule { get; set; }
        public virtual TypeFieldMedicalModule TypeFieldMedicalModule { get; set; }
    }
}
