//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabletConfiguration
    {
        public int id { get; set; }
        public Nullable<int> cdgimnasio { get; set; }
        public Nullable<int> branchId { get; set; }
        public Nullable<int> formId { get; set; }
        public Nullable<int> tabletId { get; set; }
    }
}
