//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAction()
        {
            this.tblActionParameters = new HashSet<tblActionParameters>();
        }
    
        public int id { get; set; }
        public string ipAddress { get; set; }
        public string strAction { get; set; }
        public System.DateTime actionDate { get; set; }
        public bool used { get; set; }
        public bool actionState { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<int> cdgimnasio { get; set; }
        public Nullable<int> intIdSucursales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActionParameters> tblActionParameters { get; set; }
    }
}
