//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConfiguracionAlertas
    {
        public int id_Alerta { get; set; }
        public Nullable<int> cdgimnasion { get; set; }
        public Nullable<bool> bit_AlertaPorRetiroClientes { get; set; }
        public Nullable<int> int_DiasRetiroEnvioAlertas { get; set; }
        public Nullable<bool> bit_ReporteDiario { get; set; }
        public Nullable<bool> bit_ReporteMensual { get; set; }
        public string str_NotificacionesMensualesPara { get; set; }
        public string str_ListaCorreosMensaulesEnviar { get; set; }
        public string str_NotificacionesDiariosPara { get; set; }
        public string str_ListaCorreosDiariosEnviar { get; set; }
        public string str_NotificacionesAlertaRetiroPara { get; set; }
    }
}
