//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExamenFisico
    {
        public int intPkExamenFisico { get; set; }
        public int intFkConsulta { get; set; }
        public string strPeso { get; set; }
        public string strTalla { get; set; }
        public string strFrecuenciaCardiaca { get; set; }
        public string strPresionArterialSistolica { get; set; }
        public string strPresionArterialDiastolica { get; set; }
        public string strTemperatura { get; set; }
        public string strRecomendacionRiesgoEspalda { get; set; }
        public string strRecomendacionRiesgoCaderaInferior { get; set; }
        public string strRecomendacionRiesgoCaderaSuperior { get; set; }
        public string strIMC { get; set; }
        public string strPorcentajeGrasa { get; set; }
        public string strAHA { get; set; }
        public string strYuhasz { get; set; }
        public string strIndiceAdiposidad { get; set; }
        public string strDensidadCorporalJacksonPollock { get; set; }
        public string strDensidadCorporalDurinWomersley { get; set; }
        public string strPorcentajeGrasaJacksonPollock { get; set; }
        public string strPorcentajeDurinWomersley { get; set; }
        public string strDistribucionCorporalJacksonPollockMagro { get; set; }
        public string strDistribucionCorporalJacksonPollockGraso { get; set; }
        public string strDistribucionCorporalDurinWomersleyMagro { get; set; }
        public string strDistribucionCorporalDurinWomersleyGraso { get; set; }
        public string strPesoProporcional { get; set; }
        public string strPesoGraso { get; set; }
        public string strRelacionCinturaCadera { get; set; }
        public string strPresionArterialMedia { get; set; }
        public string strDobleProducto { get; set; }
        public int intEmpresa { get; set; }
        public bool bitActivo { get; set; }
        public string strUsuarioCreacion { get; set; }
        public System.DateTime datFechaCreacion { get; set; }
        public string strUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> datFechaModificacion { get; set; }
        public string strIdealPeso { get; set; }
        public string strIdealPesoMagro { get; set; }
        public string strIdealIMC { get; set; }
        public string strIdealPorcentajeGrasa { get; set; }
        public string strIdealDias { get; set; }
        public string strIdealHorasSemanales { get; set; }
        public Nullable<int> intFKSomatotipo { get; set; }
        public Nullable<bool> bitAdams { get; set; }
        public string strObservacionAdams { get; set; }
        public string PorcentajeMasaMuscular { get; set; }
        public string GrasaVisceral { get; set; }
        public string CaloriasBasales { get; set; }
        public Nullable<int> FuerzaAbdominal { get; set; }
        public string ObservacionFuerzaAbdominal { get; set; }
        public Nullable<int> ValoracionCore { get; set; }
        public string ObservacionCore { get; set; }
        public Nullable<bool> SentadillaBasica { get; set; }
        public string ObservacionSentadillaB { get; set; }
        public Nullable<bool> SentadillaProfunda { get; set; }
        public string ObseracionSentadillaP { get; set; }
    
        public virtual tblConsulta tblConsulta { get; set; }
        public virtual tblSomatotipo tblSomatotipo { get; set; }
    }
}
