//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblErroresFacturacion
    {
        public int intpkIdError { get; set; }
        public Nullable<System.DateTime> dtmFechaError { get; set; }
        public string strIdentificacionClienteError { get; set; }
        public string strTransaccionGeneroError { get; set; }
        public string strMensajeError { get; set; }
    }
}
