//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEjercicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEjercicios()
        {
            this.tblEjerciciosContraindicados = new HashSet<tblEjerciciosContraindicados>();
            this.tblEjerciciosRecomendados = new HashSet<tblEjerciciosRecomendados>();
            this.tblRutinaEjercicio = new HashSet<tblRutinaEjercicio>();
            this.tblRutinaEjercicioCliente = new HashSet<tblRutinaEjercicioCliente>();
        }
    
        public int intPkEjercicio { get; set; }
        public Nullable<int> intFkGrupoMuscular { get; set; }
        public string strDescripcion { get; set; }
        public int intEmpresa { get; set; }
        public bool bitActivo { get; set; }
        public string strUsuarioCreacion { get; set; }
        public System.DateTime datFechaCreacion { get; set; }
        public string strUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> datFechaModificacion { get; set; }
        public Nullable<int> intFKMaquina { get; set; }
        public Nullable<int> intFKVideoEjercicio { get; set; }
        public Nullable<int> intFKImagenEjercicio { get; set; }
        public string strTipoEjercicio { get; set; }
        public string strObservacion { get; set; }
        public string strUbicacionGim { get; set; }
        public string strTips { get; set; }
        public Nullable<int> intTipoMedicion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEjerciciosContraindicados> tblEjerciciosContraindicados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEjerciciosRecomendados> tblEjerciciosRecomendados { get; set; }
        public virtual tblImagenEjercicio tblImagenEjercicio { get; set; }
        public virtual tblMaquinas tblMaquinas { get; set; }
        public virtual tblVideosEjercicios tblVideosEjercicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRutinaEjercicio> tblRutinaEjercicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRutinaEjercicioCliente> tblRutinaEjercicioCliente { get; set; }
    }
}
