//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaises
    {
        public int intID { get; set; }
        public int pai_codigo { get; set; }
        public string pai_nombre { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public string pai_equivalencia { get; set; }
        public string bits_replica { get; set; }
        public Nullable<bool> pai_modificado { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<int> intCodigoDeZonaHoraria { get; set; }
        public string Prefijo { get; set; }
        public string codigo_string { get; set; }
    }
}
