//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRutinas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRutinas()
        {
            this.tblRutinaEjercicio = new HashSet<tblRutinaEjercicio>();
            this.tblRutinaXObjetivos = new HashSet<tblRutinaXObjetivos>();
        }
    
        public int intPKRutina { get; set; }
        public string strDescripcion { get; set; }
        public int intDiasRutina { get; set; }
        public bool bitActivo { get; set; }
        public int intEmpresa { get; set; }
        public string strUsuarioCreacion { get; set; }
        public string strUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> datFechaCreacion { get; set; }
        public Nullable<System.DateTime> datFechaModificacion { get; set; }
        public Nullable<int> intTipoRutina { get; set; }
        public int intOrientado { get; set; }
        public string strCiclo { get; set; }
        public string strIdentificacionEmpleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRutinaEjercicio> tblRutinaEjercicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRutinaXObjetivos> tblRutinaXObjetivos { get; set; }
    }
}
