//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRutinaEjercicio
    {
        public int intPKRutinaEjercicio { get; set; }
        public int intFKRutina { get; set; }
        public int intFKEjercicio { get; set; }
        public int intFKTipoEjercicio { get; set; }
        public int intEmpresa { get; set; }
        public int intDia { get; set; }
        public int intSecuencia { get; set; }
        public int intCircuito { get; set; }
        public Nullable<int> intTiempo { get; set; }
        public string strIntensidad { get; set; }
        public string intPulso { get; set; }
        public Nullable<int> intSeries { get; set; }
        public Nullable<int> intRepeticiones { get; set; }
        public string intCarga { get; set; }
        public Nullable<double> floPeso { get; set; }
        public Nullable<int> intVelocidad { get; set; }
        public Nullable<int> intDescanso { get; set; }
    
        public virtual tblEjercicios tblEjercicios { get; set; }
        public virtual tblRutinas tblRutinas { get; set; }
        public virtual tblRutinaTipoEjercicio tblRutinaTipoEjercicio { get; set; }
    }
}
