//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVersion()
        {
            this.NoveltyByVersion = new HashSet<NoveltyByVersion>();
            this.VersionByUser = new HashSet<VersionByUser>();
        }
    
        public int id { get; set; }
        public string strVersion { get; set; }
        public bool bitState { get; set; }
        public bool bitDelete { get; set; }
        public System.DateTime creationDate { get; set; }
        public string creationUser { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string modifiedUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoveltyByVersion> NoveltyByVersion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VersionByUser> VersionByUser { get; set; }
    }
}
