//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogAppMobile
    {
        public int intID { get; set; }
        public string strIdentificacion { get; set; }
        public Nullable<System.DateTime> dtmFecha { get; set; }
        public Nullable<int> intSucursal { get; set; }
        public Nullable<int> cdgimnasio { get; set; }
    }
}
