//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spRegitroEnvioSMS_Result
    {
        public int id { get; set; }
        public Nullable<int> cdgimnasio { get; set; }
        public Nullable<int> idsucursal { get; set; }
        public string identificacion { get; set; }
        public string celular { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> bitEnviado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
