//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationMedicalModule
    {
        public int ConfigurationMedicalModuleID { get; set; }
        public int ModuleID { get; set; }
        public int SectionID { get; set; }
        public int cdgimnasio { get; set; }
        public int Order { get; set; }
        public int Type { get; set; }
        public Nullable<int> RootID { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string UserCreation { get; set; }
        public Nullable<System.DateTime> DateModify { get; set; }
        public string UserModify { get; set; }
        public bool State { get; set; }
        public bool Mandatory { get; set; }
    
        public virtual ModuleMedicalModule ModuleMedicalModule { get; set; }
        public virtual SectionMedicalModule SectionMedicalModule { get; set; }
    }
}
