//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficioPlan
    {
        public int IdBenePlan { get; set; }
        public Nullable<int> cdgimnasio { get; set; }
        public Nullable<int> IdPlan { get; set; }
        public Nullable<int> IdBeneficio { get; set; }
        public Nullable<int> OrdenBeneficio { get; set; }
    }
}
