//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gym_Social_Networks
    {
        public int gymId { get; set; }
        public int social_network_id { get; set; }
        public string application_id { get; set; }
        public string application_key { get; set; }
        public System.DateTime creation_date { get; set; }
        public string creation_user { get; set; }
    
        public virtual gim_gimnasio gim_gimnasio { get; set; }
        public virtual Social_Networks Social_Networks { get; set; }
    }
}
