//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spContracts_Result
    {
        public double dtcont_doc_cliente { get; set; }
        public string Nombre { get; set; }
        public string cli_mail { get; set; }
        public int dtcont_numcontrato { get; set; }
        public System.DateTime dtcont_fecha_firma { get; set; }
        public int dtcont_numero_plan { get; set; }
        public string dtcont_tipo_plan { get; set; }
        public byte[] dtcont_huella_cliente { get; set; }
        public string suc_strNombre { get; set; }
        public string cont_texto { get; set; }
        public byte[] cont_firma_responsable { get; set; }
        public string tipo_contrato { get; set; }
        public string gim_nit { get; set; }
        public string gim_nombre_gimnasio { get; set; }
        public string gim_direccion { get; set; }
        public string gim_telefono { get; set; }
        public byte[] gim_logo { get; set; }
    }
}
