//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaestroVariablePresupuesto
    {
        public int intPKVariable { get; set; }
        public string strDescripcion { get; set; }
        public string strSimbolo { get; set; }
        public Nullable<bool> bitIsInformeConsolidado { get; set; }
        public Nullable<bool> bitIsCantidad { get; set; }
        public Nullable<bool> bitIsIngresos { get; set; }
        public Nullable<bool> bitIsFormaPago { get; set; }
    }
}
