//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_planes_paquete
    {
        public int intpkIdPaquete { get; set; }
        public int pla_codigo_ppal { get; set; }
        public int pla_codigo_paquete { get; set; }
        public int cdgimnasio { get; set; }
    
        public virtual gim_planes gim_planes { get; set; }
        public virtual gim_planes gim_planes1 { get; set; }
    }
}
