//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spConfigCodigo_Nota_Creditos_Result
    {
        public int Id { get; set; }
        public int Codigo { get; set; }
        public int cdgimnasio { get; set; }
        public string NombreNumeracion { get; set; }
        public int NumeroInicialNC { get; set; }
        public int NumeroFinalNC { get; set; }
        public int NumeroActualNC { get; set; }
        public Nullable<bool> bitEstado { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
