//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Branches_Entry
    {
        public int id { get; set; }
        public int id_gym { get; set; }
        public int id_branch { get; set; }
        public string id_user { get; set; }
        public Nullable<bool> state { get; set; }
    }
}
