//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEL_Datos_Comercio
    {
        public string conf_Identificador { get; set; }
        public string conf_LlaveTransaccional { get; set; }
        public string conf_LlaveMD5 { get; set; }
        public decimal conf_ValorHasta { get; set; }
        public int cdgimnasio { get; set; }
        public int conf_IdSucursal { get; set; }
        public string MerchantId { get; set; }
        public string AccountId { get; set; }
    }
}
