//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spRptCobrosAdicionales_Inactivo_Result
    {
        public Nullable<double> TOTAL_FACTURA { get; set; }
        public int IDSUCURSAL { get; set; }
        public string SUCURSAL { get; set; }
        public int IDCLASIFICACION { get; set; }
        public string CLASIFICACION { get; set; }
        public string COBRO_ADICIONAL { get; set; }
        public int FACTURA { get; set; }
    }
}
