//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gym_Account_Types
    {
        public int gymId { get; set; }
        public int account_type_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public string creation_user { get; set; }
    
        public virtual AccountTypes AccountTypes { get; set; }
    }
}
