//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_foodTypeDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gim_foodTypeDetail()
        {
            this.gim_foodDetail = new HashSet<gim_foodDetail>();
        }
    
        public int PK_foodTypeDetailId { get; set; }
        public int FK_foodTypeId { get; set; }
        public int FK_nutritionGuideId { get; set; }
        public int cdgimnasio { get; set; }
        public int foodTypeOrder { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gim_foodDetail> gim_foodDetail { get; set; }
        public virtual gim_foodTypes gim_foodTypes { get; set; }
        public virtual gim_nutritionGuide gim_nutritionGuide { get; set; }
    }
}
