//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion_Generica
    {
        public int PileID { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Receptor { get; set; }
        public string CustomerTelephone { get; set; }
        public int cdgimnasio { get; set; }
        public System.DateTime DateStartPlan { get; set; }
        public System.DateTime DateEndPlan { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationUser { get; set; }
    }
}
