//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_Campanas
    {
        public int intID { get; set; }
        public string strNombreCampaña { get; set; }
        public string CodigoPromocional { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string Terminos_Condiciones { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFinaliza { get; set; }
        public Nullable<System.DateTime> HoraInicia { get; set; }
        public Nullable<System.DateTime> HoraFin { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<double> PorcentajeDescuento { get; set; }
        public Nullable<double> valorDescuento { get; set; }
        public Nullable<int> CantidadDeUsos { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<int> Usos { get; set; }
    }
}
