//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spVersionByUser_Result
    {
        public int id { get; set; }
        public int versionId { get; set; }
        public string userId { get; set; }
        public string userType { get; set; }
        public System.DateTime dateOfView { get; set; }
    }
}
