//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPagos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogPagos()
        {
            this.LogPagosDetalle = new HashSet<LogPagosDetalle>();
        }
    
        public int LogId { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaMto { get; set; }
        public string MetodoPago { get; set; }
        public string MedioPago { get; set; }
        public string Banco { get; set; }
        public Nullable<int> PelTransaccion__IdTransaccion { get; set; }
        public string Token { get; set; }
        public string PelTransaccion__Referencia { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<int> SucursalId { get; set; }
        public Nullable<int> GimnasioId { get; set; }
        public Nullable<System.DateTime> FechaSiguientePago { get; set; }
        public Nullable<int> FacturaId { get; set; }
        public Nullable<int> LoteId { get; set; }
        public Nullable<int> CobroCuentaId { get; set; }
        public Nullable<bool> huerfano { get; set; }
        public string Identificacion { get; set; }
        public Nullable<decimal> ValorSI { get; set; }
        public Nullable<decimal> ValorCI { get; set; }
        public Nullable<decimal> ValorASI { get; set; }
        public Nullable<decimal> ValorACI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogPagosDetalle> LogPagosDetalle { get; set; }
    }
}
