//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spConsultaPlanPorFactura_Result
    {
        public int plusu_numero_fact { get; set; }
        public Nullable<int> id { get; set; }
        public string detalle { get; set; }
        public Nullable<int> poriva { get; set; }
        public string tipo { get; set; }
        public Nullable<double> valoriva { get; set; }
        public Nullable<double> valoruni { get; set; }
        public Nullable<double> valortotal { get; set; }
        public Nullable<int> cantidad { get; set; }
    }
}
