//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_codigo_cliente
    {
        public int gim_con_cod { get; set; }
        public string gim_tip_cod { get; set; }
        public Nullable<int> gim_num_cod { get; set; }
        public Nullable<double> gim_ced_cli_cod { get; set; }
        public string gim_codigo { get; set; }
        public Nullable<System.DateTime> gim_fec_cod { get; set; }
        public Nullable<System.DateTime> gim_fec_ult_ing { get; set; }
        public bool gim_cod_modificado { get; set; }
    }
}
