//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class sp_ReservasClienteFactura_Result
    {
        public string Tabla { get; set; }
        public Nullable<int> cdplusu { get; set; }
        public string tipo_Corte_Fact { get; set; }
        public System.DateTime fecha_clase { get; set; }
    }
}
