//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultationBodySegment
    {
        public int ConsultationBodySegmentID { get; set; }
        public int MedicalConsultationID { get; set; }
        public int BodySegmentID { get; set; }
        public string PreviousView { get; set; }
        public string RearView { get; set; }
        public string SideView { get; set; }
    
        public virtual BodySegment BodySegment { get; set; }
        public virtual MedicalConsultation MedicalConsultation { get; set; }
    }
}
