//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spPlanesUsuario_Result
    {
        public int NRO { get; set; }
        public Nullable<int> CodPlan { get; set; }
        public string PRODUCTO { get; set; }
        public string Documento { get; set; }
        public string CLIENTE { get; set; }
        public string F__COMPRA { get; set; }
        public string MES_COMPRA { get; set; }
        public Nullable<int> AÑO_COMPRA { get; set; }
        public string F__VENCIMIENTO { get; set; }
        public string F__INICIO { get; set; }
        public Nullable<double> VALOR { get; set; }
        public Nullable<double> IVA { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public string Plan_Tipo_Tarifa { get; set; }
        public string Plan_pertenece_a { get; set; }
        public string Vendido_en { get; set; }
        public string Empleado { get; set; }
        public string Comercial { get; set; }
        public Nullable<bool> Anulada { get; set; }
        public string FechaAnulada { get; set; }
        public Nullable<bool> Finalizado { get; set; }
        public string TipoVenta { get; set; }
        public string Factura_Como_Supo { get; set; }
        public string Cliente___F_Nac { get; set; }
        public Nullable<int> Cliente___Edad { get; set; }
        public string Cliente___F__Ingreso { get; set; }
        public string Cliente___Dirección { get; set; }
        public string Cliente___Email { get; set; }
        public string Cliente___Telefono { get; set; }
        public string Cliente___Celular { get; set; }
        public Nullable<double> Cliente___Fax { get; set; }
        public Nullable<double> Cliente___Tel__Oficina { get; set; }
        public string Cliente___Tipo_Sangre { get; set; }
        public string Cliente___Sexo { get; set; }
        public string Cliente___Sucursal { get; set; }
        public string Cliente___Como_Supo { get; set; }
        public string Cliente___Profesión { get; set; }
        public string Cliente___Barrio { get; set; }
        public Nullable<int> Cliente___Hijos { get; set; }
        public string Cliente___Universidad { get; set; }
        public string Cliente___EPS { get; set; }
        public string Cliente___Hobbie_Ppal { get; set; }
        public string Cliente___Nivel_Ingreso { get; set; }
        public string Cliente___Opcional_1 { get; set; }
        public string Cliente___Opcional_2 { get; set; }
        public string Cliente___Opcional_3 { get; set; }
        public Nullable<int> Numero_entradas_durante_ultima_semana { get; set; }
        public Nullable<int> Promedio_tiempo_de_permanencia_durante_plan_vigente { get; set; }
        public string Factura_Nueva_o_Renovada { get; set; }
        public string Autorizacion { get; set; }
        public Nullable<bool> Bolsa_de_dinero { get; set; }
        public int Resolucion { get; set; }
        public string Observaciones { get; set; }
        public string DebitoAutomatico { get; set; }
        public string Formas_de_Pago { get; set; }
    }
}
