//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spConsultarClientePlanValidacion_Result
    {
        public string ID { get; set; }
        public string CLIENTE { get; set; }
        public string PLANU { get; set; }
        public Nullable<int> CODPLAN { get; set; }
        public Nullable<int> pla_codigo { get; set; }
        public string TIENERESERVA { get; set; }
    }
}
