//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_detalle_pantalla
    {
        public int detpant_PKcodigo { get; set; }
        public int detpant_FKpantalla { get; set; }
        public string detpant_nombretecnico { get; set; }
        public string detpant_nombrevisible { get; set; }
        public bool detpant_todos { get; set; }
        public bool detpant_lectura { get; set; }
        public bool detpant_ninguno { get; set; }
        public bool detpant_exportxls { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
    }
}
