//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MvtoActividad
    {
        public System.DateTime datFechaCreacion { get; set; }
        public int cdempleado { get; set; }
        public string strResultado { get; set; }
        public int estado { get; set; }
        public Nullable<bool> bitRenueva { get; set; }
        public string strPorque { get; set; }
        public int intMvto_Actividad { get; set; }
        public int intFkIdModComProgramaActividad { get; set; }
        public Nullable<System.DateTime> dtmFechaPospuesta { get; set; }
    }
}
