//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_reserva_telefonica
    {
        public int cdreserva { get; set; }
        public int cdcliente { get; set; }
        public int cdclase { get; set; }
        public int cdgimnasio { get; set; }
        public int cdhorario_clase { get; set; }
        public System.DateTime fecha_clase { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_reserva { get; set; }
        public int res_modificado { get; set; }
    }
}
