//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spPeriodDetailBuy_Result
    {
        public int Código { get; set; }
        public int Código_Configuración { get; set; }
        public int Mes_Inicial { get; set; }
        public int Mes_Final { get; set; }
        public int Mes_de_Pago { get; set; }
    }
}
