//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_centro_notificaciones
    {
        public int cdgimnasio { get; set; }
        public string identificacion { get; set; }
        public int noti_codigo { get; set; }
        public string noti_tipo { get; set; }
        public string noti_titulo { get; set; }
        public string noti_descripcion { get; set; }
        public Nullable<System.DateTime> noti_fecha { get; set; }
        public bool noti_estado { get; set; }
        public string noti_url { get; set; }
    }
}
