//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spConsultarPacientesPlanUsuarioYPUEspecial_Result
    {
        public string cli_identifi { get; set; }
        public string cli_nombres { get; set; }
        public string cli_primer_apellido { get; set; }
        public string cli_segundo_apellido { get; set; }
    }
}
