//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRutinaXObjetivosClientes
    {
        public int intPKRutinaXObjetivos { get; set; }
        public int intFKRutina { get; set; }
        public int intFKObjetivos { get; set; }
        public int intEmpresa { get; set; }
    
        public virtual tblObjetivos tblObjetivos { get; set; }
        public virtual tblRutinasClientes tblRutinasClientes { get; set; }
    }
}
