//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_reservas
    {
        public int cdreserva { get; set; }
        public string IdentificacionCliente { get; set; }
        public Nullable<int> cdplusu { get; set; }
        public int cdclase { get; set; }
        public int cdgimnasio { get; set; }
        public int cdhorario_clase { get; set; }
        public System.DateTime fecha_clase { get; set; }
        public string intensidad { get; set; }
        public string estado { get; set; }
        public int tiq_utilizados { get; set; }
        public int tiq_vigentes_al_reservar { get; set; }
        public int megas_utilizadas { get; set; }
        public int megas_vigentes_al_reservar { get; set; }
        public System.DateTime fecha_ultima_reserva { get; set; }
        public string observaciones_cancela { get; set; }
        public int cdultima_reserva { get; set; }
        public System.DateTime fecha_maxima_cancelacion { get; set; }
        public string descripcion_plan { get; set; }
        public string tipo_plan { get; set; }
        public System.DateTime fecha_vigencia_plan { get; set; }
        public string dias_disponibles_plan { get; set; }
        public int res_modificado { get; set; }
        public string ubi_reserva { get; set; }
        public Nullable<int> fksalon { get; set; }
        public string observaciones_asistencia { get; set; }
        public Nullable<int> dias_gracia { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public Nullable<int> estadoImpreso { get; set; }
        public Nullable<int> cdsucursal { get; set; }
        public string bits_replica { get; set; }
        public string tipo_Corte_Fact { get; set; }
    }
}
