//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spConsultarRutina_Result
    {
        public string cli_identifi { get; set; }
        public string Nombre { get; set; }
        public int intPKRutina { get; set; }
        public string strDescripcion { get; set; }
        public string strCiclo { get; set; }
        public int intDiasRutina { get; set; }
        public bool bitActivo { get; set; }
        public int intEmpresa { get; set; }
        public Nullable<int> intTipoRutina { get; set; }
        public string nombreEmp { get; set; }
        public string FechaAsignacion { get; set; }
        public int intPKRutina1 { get; set; }
        public string strIdentificacionCliente { get; set; }
        public string strDescripcion1 { get; set; }
        public int intDiasRutina1 { get; set; }
        public bool bitActivo1 { get; set; }
        public int intEmpresa1 { get; set; }
        public string strUsuarioCreacion { get; set; }
        public string strUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> datFechaCreacion { get; set; }
        public Nullable<System.DateTime> datFechaModificacion { get; set; }
        public Nullable<System.DateTime> datVigencia { get; set; }
        public Nullable<int> intPlantilla { get; set; }
        public Nullable<int> intTipoRutina1 { get; set; }
        public string strComentarios { get; set; }
        public Nullable<bool> bitSolicitaMedicion { get; set; }
        public Nullable<int> intMedicion { get; set; }
        public string strCiclo1 { get; set; }
        public string strIdentificacionEmpleado { get; set; }
    }
}
