//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spInformationGraphics_Result
    {
        public Nullable<double> strPeso { get; set; }
        public Nullable<double> strPesoGraso { get; set; }
        public Nullable<double> strIMC { get; set; }
        public Nullable<double> strPorcentajeGrasa { get; set; }
        public Nullable<double> strIdealPeso { get; set; }
        public string strIdealPesoMagro { get; set; }
        public string strIdealIMC { get; set; }
        public Nullable<double> strIdealPorcentajeGrasa { get; set; }
        public Nullable<int> strIdealDias { get; set; }
        public Nullable<int> strIdealHorasSemanales { get; set; }
    }
}
