//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodicity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Periodicity()
        {
            this.AdminFeeConfiguration = new HashSet<AdminFeeConfiguration>();
        }
    
        public int per_intId { get; set; }
        public string per_strDescription { get; set; }
        public bool per_bitState { get; set; }
        public string per_strModifiedUser { get; set; }
        public System.DateTime per_dtmModifiedDate { get; set; }
        public int cdgimnasio { get; set; }
        public string bits_replica { get; set; }
        public Nullable<bool> per_bitModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminFeeConfiguration> AdminFeeConfiguration { get; set; }
    }
}
