//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spRptClients_Result
    {
        public string cli_identifiString { get; set; }
        public string cli_identifi { get; set; }
        public string clientName { get; set; }
        public string phone { get; set; }
        public string cellPhone { get; set; }
        public string barrio { get; set; }
        public string genre { get; set; }
        public string dayMonth { get; set; }
        public string dateBorn { get; set; }
        public string clientAddress { get; set; }
        public string dateEntry { get; set; }
        public string howKnew { get; set; }
        public string mail { get; set; }
        public string university { get; set; }
        public string eps { get; set; }
        public string profesion { get; set; }
        public string clientGroup { get; set; }
        public string subGroup { get; set; }
        public string hobbie { get; set; }
        public string nivelIngresos { get; set; }
        public string branchName { get; set; }
        public string company { get; set; }
        public double referido { get; set; }
        public double comercial { get; set; }
        public int planId { get; set; }
        public int locker { get; set; }
        public string grupoFamiliar { get; set; }
        public string envioMail { get; set; }
        public string envioSMS { get; set; }
        public string autorizaInfo { get; set; }
        public string autorizaHuella { get; set; }
        public string codCard { get; set; }
        public string fechaTermCondiciones { get; set; }
        public string fechaConsentimiento { get; set; }
        public Nullable<int> estrato { get; set; }
        public Nullable<int> edad { get; set; }
        public string Ult_plan_entrenamiento { get; set; }
        public string Plan_entrenamiento_vigente { get; set; }
        public System.DateTime Fecha_vigencia_plan_entrenamiento { get; set; }
        public System.DateTime Fecha_asignación_plan_entrenamiento { get; set; }
        public string Empleado_asigno_plan_entrenamiento { get; set; }
        public string ExentoCuotaAdministracion { get; set; }
        public string MotivoExentoCuotaAdministracion { get; set; }
        public string HuellaRegistrada { get; set; }
        public Nullable<bool> EstadoCliente { get; set; }
        public bool IngresoSinHuella { get; set; }
    }
}
