//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_foods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gim_foods()
        {
            this.gim_foodDetail = new HashSet<gim_foodDetail>();
        }
    
        public int PK_foodId { get; set; }
        public int FK_foodTypeId { get; set; }
        public int cdgimnasio { get; set; }
        public string Description { get; set; }
        public bool bit_state { get; set; }
        public byte[] photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gim_foodDetail> gim_foodDetail { get; set; }
        public virtual gim_foodTypes gim_foodTypes { get; set; }
    }
}
