//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spReporteContratoIndividual_Result
    {
        public double ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> contra { get; set; }
        public int CONTRATO { get; set; }
        public System.DateTime FECHA_FIRMA { get; set; }
        public int NUMERO { get; set; }
        public string TIPO_PLAN { get; set; }
        public string Title { get; set; }
        public string TIPO { get; set; }
        public string ACUDIENTE { get; set; }
        public string SUCURSAL { get; set; }
        public string TEXTO_CONTRATO { get; set; }
        public string cont_firma_responsable { get; set; }
        public string tipo_contrato { get; set; }
        public Nullable<int> gim_codigo_contrato { get; set; }
        public string tipoIdentificacion { get; set; }
        public string correo { get; set; }
        public string nombreSedeComproPlan { get; set; }
        public string nombrePlan { get; set; }
        public double costoPlan { get; set; }
        public string fechaInicioPlan { get; set; }
        public double ValorCuotaDeAdministracion { get; set; }
        public string FechaCobroRecurrente { get; set; }
    }
}
