//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_gastos
    {
        public long g_intNumeroEgreso { get; set; }
        public Nullable<int> g_intIdTipoGasto { get; set; }
        public Nullable<int> g_intIdSubGrupoTipoGasto { get; set; }
        public Nullable<int> g_intIdProveedor { get; set; }
        public Nullable<double> g_floValor { get; set; }
        public string g_strFormaPago { get; set; }
        public string g_strNota { get; set; }
        public Nullable<System.DateTime> g_dtmFechaCreacion { get; set; }
        public Nullable<int> g_intIdSucursal { get; set; }
        public int cdgimnasio { get; set; }
        public string g_estado { get; set; }
        public string g_motivo_anulacion { get; set; }
        public System.DateTime dtmFechaGasto { get; set; }
    }
}
