//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_entradas_usuarios
    {
        public int enusu_numero { get; set; }
        public string enusu_identifi { get; set; }
        public Nullable<int> enusu_plan { get; set; }
        public Nullable<System.DateTime> enusu_fecha_entrada { get; set; }
        public Nullable<System.DateTime> enusu_hora_entrada { get; set; }
        public Nullable<System.DateTime> enusu_fecha_salida { get; set; }
        public Nullable<System.DateTime> enusu_hora_salida { get; set; }
        public short enusu_sucursal { get; set; }
        public Nullable<int> enusu_modificado { get; set; }
        public Nullable<int> enusu_sede { get; set; }
        public string enusu_referenciacodigo { get; set; }
        public string enusu_referenciadesc { get; set; }
        public string enusu_strtipoventa { get; set; }
        public Nullable<int> enusu_intnumero { get; set; }
        public Nullable<bool> enusu_blnrestotiquete { get; set; }
        public string enusu_strconcepto { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<bool> enusu_modificado_TG { get; set; }
        public string bits_replica { get; set; }
        public Nullable<int> enusu_VisitId { get; set; }
        public string entryCode { get; set; }
        public Nullable<decimal> entryTemperature { get; set; }
        public string exitCode { get; set; }
        public Nullable<decimal> exitTemperature { get; set; }
        public Nullable<bool> bitPuntos { get; set; }
    }
}
