//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_CancelacionPlan
    {
        public int can_IdCancelacion { get; set; }
        public string can_strIdentificacionCliente { get; set; }
        public string can_strTipoCancelacion { get; set; }
        public Nullable<int> can_intIdMotivoCancel { get; set; }
        public System.DateTime can_dtmFechaCancelacion { get; set; }
        public int can_intIdPlanCancelado { get; set; }
        public int can_intIdSucursal { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<int> can_id_recurrencia { get; set; }
        public string can_comentarios { get; set; }
        public Nullable<int> can_intCancelationType { get; set; }
    }
}
