//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spRptIngresosAdicionales_Result
    {
        public Nullable<System.DateTime> adi_fecha { get; set; }
        public Nullable<System.DateTime> adi_hora { get; set; }
        public string adi_descripcion { get; set; }
        public string suc_strNombre { get; set; }
    }
}
