//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_tipo_empleado
    {
        public int id { get; set; }
        public int cdgimnasio { get; set; }
        public int tipoemp_codigo { get; set; }
        public string tipoemp_descripcion { get; set; }
        public Nullable<bool> tipoemp_coequipero { get; set; }
        public Nullable<int> tipoemp_prerequisito_liqinct { get; set; }
        public Nullable<int> tipoemp_modificado { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public Nullable<bool> tipoemp_AfecDNL { get; set; }
        public Nullable<bool> tipoemp_estado { get; set; }
    }
}
