//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_detalle_cobro
    {
        public int det_numero { get; set; }
        public Nullable<int> det_numero_factura { get; set; }
        public Nullable<int> det_codigo_cobro { get; set; }
        public Nullable<short> det_codigo_pago { get; set; }
        public Nullable<double> det_valor_pago { get; set; }
        public byte det_sucursal { get; set; }
        public bool det_modificado { get; set; }
        public Nullable<int> det_sede { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
    }
}
