//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aliados
    {
        public int Id { get; set; }
        public Nullable<int> cdgimnasio { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string CondicionesyRestricciones { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<int> IdPais { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Horarios { get; set; }
        public string FacebookURL { get; set; }
        public string InstagramURL { get; set; }
        public string WhatsApp { get; set; }
        public string Descuento { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    }
}
