//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spRptClientesConPlan_Result
    {
        public Nullable<int> plusu_codigo_plan { get; set; }
        public string pla_descripc { get; set; }
        public string pla_tipo { get; set; }
        public Nullable<int> pla_cantidad { get; set; }
        public Nullable<int> plusu_tiq_disponible { get; set; }
        public Nullable<int> consumo { get; set; }
        public Nullable<double> pla_valor { get; set; }
        public string Tipo { get; set; }
        public double plusu_numero_fact { get; set; }
        public Nullable<System.DateTime> plusu_fecha_compra { get; set; }
        public string plusu_identifi_cliente { get; set; }
        public string nombre { get; set; }
        public Nullable<double> plusu_descuento { get; set; }
        public string cli_telefono { get; set; }
        public string cli_celular { get; set; }
        public Nullable<double> plusu_valor_iva { get; set; }
        public Nullable<double> valor { get; set; }
        public string plusu_forma_pago { get; set; }
        public Nullable<System.DateTime> plusu_fecha_vcto { get; set; }
        public Nullable<int> Edad { get; set; }
        public string cli_direccio { get; set; }
        public Nullable<System.DateTime> plusu_fecha_inicio { get; set; }
        public string cli_mail { get; set; }
        public string suc_strNombre { get; set; }
    }
}
