//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Not_Saved_Clients_WS
    {
        public int intId { get; set; }
        public string strClientId { get; set; }
        public int intTriesNumber { get; set; }
        public bool bitSaved { get; set; }
        public System.DateTime dateRegister { get; set; }
        public string strInitialMessage { get; set; }
        public Nullable<System.DateTime> dateLastTry { get; set; }
        public string strMessageLog { get; set; }
        public Nullable<bool> bitModified { get; set; }
        public int cdgimnasio { get; set; }
        public string bits_replica { get; set; }
    }
}
