//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_formas_pago
    {
        public int pag_codigo { get; set; }
        public string pag_descrip { get; set; }
        public Nullable<int> pag_modificado { get; set; }
        public Nullable<bool> pag_generacredito { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public string pag_codigo_web { get; set; }
        public Nullable<int> pag_tipo { get; set; }
        public Nullable<bool> pag_solic_comprobante { get; set; }
        public string bits_replica { get; set; }
        public int intId { get; set; }
        public string pag_CtaContable { get; set; }
        public string pag_CodigoCaja { get; set; }
        public string pag_CodigoCtaBancaria { get; set; }
        public string pag_ConceptoFlujoCaja { get; set; }
        public string pag_NaturalezaTccion { get; set; }
        public string pag_IndicadorMvto { get; set; }
        public string pag_TipoMvto { get; set; }
        public string pag_CodCondPago { get; set; }
        public string pag_TipoDoctoPago { get; set; }
        public bool pag_ventaennet { get; set; }
        public bool pag_ventaenweb { get; set; }
        public Nullable<bool> pag_estado { get; set; }
        public Nullable<bool> pagounico { get; set; }
        public Nullable<bool> pagorecurrente { get; set; }
        public Nullable<bool> bitSolicitarProveedorDatafonos { get; set; }
        public Nullable<int> intProveedorDatafonos { get; set; }
        public Nullable<bool> bitSolicitaNumerodeLote { get; set; }
        public string PlataformaExterna { get; set; }
        public Nullable<bool> bit_Solicita_numero_del_cheque { get; set; }
        public Nullable<bool> bit_Solicita_nombre_del_banco { get; set; }
        public Nullable<bool> bit_Solicita_detalle { get; set; }
    }
}
