//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditNote()
        {
            this.CreditNoteDetail = new HashSet<CreditNoteDetail>();
        }
    
        public int CreditNoteID { get; set; }
        public int GYMID { get; set; }
        public string ClientID { get; set; }
        public int InvoiceID { get; set; }
        public int BranchID { get; set; }
        public int DianID { get; set; }
        public int ConceptCreditNoteID { get; set; }
        public double CreditNoteValue { get; set; }
        public double CreditNoteValueIVA { get; set; }
        public double CreditNoteTotalValue { get; set; }
        public string Comment { get; set; }
        public string DocumentID { get; set; }
        public Nullable<int> TechnologicalSupplierID { get; set; }
        public Nullable<bool> Modified { get; set; }
        public string bits_replica { get; set; }
        public string CreationUser { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string EstablishmentInvoiceNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> CodigoNotaCredito { get; set; }
        public Nullable<int> NumeroNotaCredito { get; set; }
        public Nullable<bool> bitDocumentoElectronicoNC { get; set; }
        public Nullable<bool> bitGrupoFamiliar { get; set; }
        public Nullable<bool> bitPuntos { get; set; }
        public Nullable<bool> bitDocumentoConErrores { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditNoteDetail> CreditNoteDetail { get; set; }
    }
}
