//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEL_ConfiguracionRecurrencia
    {
        public int idRecurencia { get; set; }
        public int cdgimnasio { get; set; }
        public string conf_strTipoReintento { get; set; }
        public int conf_intNumeroDias { get; set; }
        public int conf_intNumeroReintentos { get; set; }
        public int conf_intDiaMes { get; set; }
    }
}
