//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCumplimientoMetas
    {
        public int intpkIdRegistro { get; set; }
        public double fltVentasPpto { get; set; }
        public double fltVentasReal { get; set; }
        public int intPorRetenPpto { get; set; }
        public int intPorRetenReal { get; set; }
        public int intClienActPpto { get; set; }
        public int intClienActReal { get; set; }
        public int intPorPropClienPpto { get; set; }
        public int intPorPropClienReal { get; set; }
        public int intActividadesPpto { get; set; }
        public int intActividadesReal { get; set; }
        public int intCdGimnasio { get; set; }
        public int intSucGym { get; set; }
        public int intAno { get; set; }
        public int intMes { get; set; }
        public int intCumpleañosMes { get; set; }
        public int intAniversariosMes { get; set; }
        public int intDiasDeProfesionesMes { get; set; }
        public int intFechasEspecialesMes { get; set; }
        public int intProspectosSinCompra { get; set; }
        public int intClientesPlanSinAsistir { get; set; }
        public int intClientesSinPlanVigente { get; set; }
        public int intClientesNuevos { get; set; }
        public int intClientesRenovados { get; set; }
        public int intClientesContinuos { get; set; }
        public int intPlanVencerseMes { get; set; }
        public int intMasCliente { get; set; }
        public string strIdComercial { get; set; }
    }
}
