//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGateway
    {
        public int PaymentGatewayID { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string UserCreation { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
        public string UserModification { get; set; }
        public Nullable<bool> Del { get; set; }
        public string UrlApi { get; set; }
        public string Code { get; set; }
        public string UrlInformation { get; set; }
        public string NameImage { get; set; }
        public Nullable<bool> Test { get; set; }
        public string urlCollect { get; set; }
    }
}
