//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPagosDetalle
    {
        public int LogDetalleId { get; set; }
        public Nullable<int> LogPagos_LogId { get; set; }
        public Nullable<System.DateTime> FechaMto { get; set; }
        public string Estado { get; set; }
        public string Descripcion { get; set; }
    
        public virtual LogPagos LogPagos { get; set; }
    }
}
