//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_detalle_pago_credito
    {
        public int det_pag_numero { get; set; }
        public int det_pag_cre_num { get; set; }
        public Nullable<int> det_pag_num_pag { get; set; }
        public Nullable<double> det_pag_val_abo { get; set; }
        public Nullable<double> det_pag_val_res { get; set; }
        public Nullable<bool> det_pag_modificado { get; set; }
        public int det_pag_sede { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public string bits_replica { get; set; }
        public Nullable<int> det_codigo_pago { get; set; }
    }
}
