//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class Pa_ReservasCorreoCambioHorario_Result
    {
        public int cdreserva { get; set; }
        public string cliente { get; set; }
        public string cli_mail { get; set; }
        public string clase { get; set; }
        public System.DateTime fecha_clase { get; set; }
        public string gim_telefono { get; set; }
        public string gim_nombre_gimnasio { get; set; }
        public System.DateTime inicio { get; set; }
        public System.DateTime hora_fin { get; set; }
    }
}
