//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnologicalSupplier
    {
        public int TechnologicalSupplierID { get; set; }
        public string Name { get; set; }
        public string UrlApi { get; set; }
        public string Code { get; set; }
        public bool Del { get; set; }
        public bool Test { get; set; }
        public string CreationUser { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModificationUser { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string Unique_code_name_FE { get; set; }
        public Nullable<bool> bitGraphic_query { get; set; }
        public Nullable<bool> bitGraphic_generation { get; set; }
        public string UrlConsultaPdfRepresentacionGrafica { get; set; }
        public string IDPdfRepresentacionGrafica { get; set; }
    }
}
