//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spPlanesClases_Result
    {
        public int cdplan { get; set; }
        public string pla_descripc { get; set; }
        public string pla_tipo { get; set; }
        public Nullable<int> pla_vigencia { get; set; }
        public Nullable<double> pla_valor { get; set; }
    }
}
