//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEL_Tokens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEL_Tokens()
        {
            this.PEL_CobrosRecurrentes = new HashSet<PEL_CobrosRecurrentes>();
        }
    
        public string tk_TokenId { get; set; }
        public string tk_UltimosCuatro { get; set; }
        public string tk_NombreBanco { get; set; }
        public string tk_Franquicia { get; set; }
        public int tk_NumeroCuotas { get; set; }
        public string tk_Identificacion { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<bool> tk_Activa { get; set; }
        public string ID_FUENTE_DE_PAGO_WOMPI { get; set; }
        public string TIPO_DE_PAGO_WOMPI { get; set; }
        public string idTarjetaConTokenOPENPAY { get; set; }
        public string DeviceSessionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEL_CobrosRecurrentes> PEL_CobrosRecurrentes { get; set; }
    }
}
