//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_detalle_perfil
    {
        public int detper_FKperfil { get; set; }
        public int detper_FKdetpantalla { get; set; }
        public int detper_FKpantalla { get; set; }
        public bool detper_todos { get; set; }
        public bool detper_lectura { get; set; }
        public bool detper_ninguno { get; set; }
        public bool detper_exportxls { get; set; }
        public Nullable<int> detper_modificado { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
    }
}
