//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_subgrupos
    {
        public int subg_intcodigo { get; set; }
        public string subg_charnombre { get; set; }
        public int subg_intcodigogrupo { get; set; }
        public decimal subg_decdescuento { get; set; }
        public int subg_intdiasadicionales { get; set; }
        public int subg_intmegasadicionales { get; set; }
        public bool subg_bitActivaValidarEdad { get; set; }
        public int subg_intEdadInicial { get; set; }
        public int subg_intEdadFinal { get; set; }
        public bool subg_modificado { get; set; }
        public bool bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public string bits_replica { get; set; }
        public Nullable<bool> bool_MostrarEdadInformes { get; set; }
        public Nullable<bool> bool_MostrarSexoInformes { get; set; }
        public string subg_strCodigoSirevac { get; set; }
        public Nullable<bool> subg_MostrarInfSubDem { get; set; }
    }
}
