//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.Servicio.ListaBlanca.wsGSW {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsGSW.Generic1Soap")]
    public interface Generic1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVideoTutorials", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sibo.Servicio.ListaBlanca.wsGSW.eTutorialVideo[] GetVideoTutorials(string formName, bool isNet, int applicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVideoTutorials", ReplyAction="*")]
        System.Threading.Tasks.Task<Sibo.Servicio.ListaBlanca.wsGSW.eTutorialVideo[]> GetVideoTutorialsAsync(string formName, bool isNet, int applicationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getClientsFilterEmployed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sibo.Servicio.ListaBlanca.wsGSW.eCliente[] getClientsFilterEmployed(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getClientsFilterEmployed", ReplyAction="*")]
        System.Threading.Tasks.Task<Sibo.Servicio.ListaBlanca.wsGSW.eCliente[]> getClientsFilterEmployedAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHuella", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sibo.Servicio.ListaBlanca.wsGSW.eHuellas[] GetHuella(int cdgimnasio, string clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHuella", ReplyAction="*")]
        System.Threading.Tasks.Task<Sibo.Servicio.ListaBlanca.wsGSW.eHuellas[]> GetHuellaAsync(int cdgimnasio, string clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHuellaGym", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sibo.Servicio.ListaBlanca.wsGSW.eHuellas[] GetHuellaGym(int cdgimnasio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHuellaGym", ReplyAction="*")]
        System.Threading.Tasks.Task<Sibo.Servicio.ListaBlanca.wsGSW.eHuellas[]> GetHuellaGymAsync(int cdgimnasio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHuellaGym2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sibo.Servicio.ListaBlanca.wsGSW.eHuellas[] GetHuellaGym2(int cdgimnasio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHuellaGym2", ReplyAction="*")]
        System.Threading.Tasks.Task<Sibo.Servicio.ListaBlanca.wsGSW.eHuellas[]> GetHuellaGym2Async(int cdgimnasio);
        
        // CODEGEN: El parámetro 'imageBytes' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validatefootprint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sibo.Servicio.ListaBlanca.wsGSW.validatefootprintResponse validatefootprint(Sibo.Servicio.ListaBlanca.wsGSW.validatefootprintRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validatefootprint", ReplyAction="*")]
        System.Threading.Tasks.Task<Sibo.Servicio.ListaBlanca.wsGSW.validatefootprintResponse> validatefootprintAsync(Sibo.Servicio.ListaBlanca.wsGSW.validatefootprintRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultadehuellasEntidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ConsultadehuellasEntidad(int cdgimnasio, string identifi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultadehuellasEntidad", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ConsultadehuellasEntidadAsync(int cdgimnasio, string identifi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWithPaymentGateway", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool getWithPaymentGateway();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWithPaymentGateway", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> getWithPaymentGatewayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWithDebitAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool getWithDebitAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWithDebitAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> getWithDebitAccountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWithPaymentGatewayEmployed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool getWithPaymentGatewayEmployed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWithPaymentGatewayEmployed", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> getWithPaymentGatewayEmployedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWithDebitAccountEmployed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool getWithDebitAccountEmployed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWithDebitAccountEmployed", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> getWithDebitAccountEmployedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResultValidationsIncome", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetResultValidationsIncome(int cdgimnasio, int idsucursal, string clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResultValidationsIncome", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetResultValidationsIncomeAsync(int cdgimnasio, int idsucursal, string clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkAutomaticDebit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool checkAutomaticDebit(int cdgimnasio, int idPlan, string idClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkAutomaticDebit", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> checkAutomaticDebitAsync(int cdgimnasio, int idPlan, string idClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIdByQR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetIdByQR(string qr, int cdgimnasio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIdByQR", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetIdByQRAsync(string qr, int cdgimnasio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/canceledForTemperature", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool canceledForTemperature(string qr, int cdgimnasio, int branch, int temperature, string id, System.DateTime entryHour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/canceledForTemperature", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> canceledForTemperatureAsync(string qr, int cdgimnasio, int branch, int temperature, string id, System.DateTime entryHour);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validationAccess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string validationAccess(string qr, int cdgimnasio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validationAccess", ReplyAction="*")]
        System.Threading.Tasks.Task<string> validationAccessAsync(string qr, int cdgimnasio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/disableAccessCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool disableAccessCodes(int codigo, int cdgimnasio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/disableAccessCodes", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> disableAccessCodesAsync(int codigo, int cdgimnasio);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class eTutorialVideo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string titleField;
        
        private string technicalNameField;
        
        private string urlField;
        
        private int applicationIdField;
        
        private int formIdField;
        
        private string formNameField;
        
        private bool stateField;
        
        private string creationUserField;
        
        private string creationDateField;
        
        private string modifiedUserField;
        
        private string modifiedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string technicalName {
            get {
                return this.technicalNameField;
            }
            set {
                this.technicalNameField = value;
                this.RaisePropertyChanged("technicalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int applicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
                this.RaisePropertyChanged("applicationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int formId {
            get {
                return this.formIdField;
            }
            set {
                this.formIdField = value;
                this.RaisePropertyChanged("formId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string formName {
            get {
                return this.formNameField;
            }
            set {
                this.formNameField = value;
                this.RaisePropertyChanged("formName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string creationUser {
            get {
                return this.creationUserField;
            }
            set {
                this.creationUserField = value;
                this.RaisePropertyChanged("creationUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string creationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("creationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string modifiedUser {
            get {
                return this.modifiedUserField;
            }
            set {
                this.modifiedUserField = value;
                this.RaisePropertyChanged("modifiedUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string modifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
                this.RaisePropertyChanged("modifiedDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class eHuellas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identificationField;
        
        private string byteHuellaField;
        
        private byte[] huellabyteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
                this.RaisePropertyChanged("identification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string byteHuella {
            get {
                return this.byteHuellaField;
            }
            set {
                this.byteHuellaField = value;
                this.RaisePropertyChanged("byteHuella");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] Huellabyte {
            get {
                return this.huellabyteField;
            }
            set {
                this.huellabyteField = value;
                this.RaisePropertyChanged("Huellabyte");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class eCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cli_identifiField;
        
        private string cli_identifiRealField;
        
        private string cli_nombresField;
        
        private string cli_apellidosField;
        
        private string cli_direccioField;
        
        private string cli_mailField;
        
        private string cli_celularField;
        
        private string cli_telefonoField;
        
        private string cli_fecha_nacimienField;
        
        private int cli_tipo_identifiField;
        
        private int cli_sexoField;
        
        private string sessionIDField;
        
        private string cokieField;
        
        private string scriptSecurityField;
        
        private int conveyanceIDField;
        
        private int profesionIDField;
        
        private string universityField;
        
        private int neighborhoodIDField;
        
        private int numberChildrenField;
        
        private int stratumIDField;
        
        private int epsIDField;
        
        private string rhField;
        
        private int prepaidHealthField;
        
        private string contactPhoneField;
        
        private string contactNameField;
        
        private int itrainingGoalsField;
        
        private string ifirstTimeGymField;
        
        private System.Nullable<int> ihowKnowField;
        
        private System.Nullable<int> idPaisField;
        
        private string rUCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cli_identifi {
            get {
                return this.cli_identifiField;
            }
            set {
                this.cli_identifiField = value;
                this.RaisePropertyChanged("cli_identifi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cli_identifiReal {
            get {
                return this.cli_identifiRealField;
            }
            set {
                this.cli_identifiRealField = value;
                this.RaisePropertyChanged("cli_identifiReal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cli_nombres {
            get {
                return this.cli_nombresField;
            }
            set {
                this.cli_nombresField = value;
                this.RaisePropertyChanged("cli_nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string cli_apellidos {
            get {
                return this.cli_apellidosField;
            }
            set {
                this.cli_apellidosField = value;
                this.RaisePropertyChanged("cli_apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string cli_direccio {
            get {
                return this.cli_direccioField;
            }
            set {
                this.cli_direccioField = value;
                this.RaisePropertyChanged("cli_direccio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string cli_mail {
            get {
                return this.cli_mailField;
            }
            set {
                this.cli_mailField = value;
                this.RaisePropertyChanged("cli_mail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string cli_celular {
            get {
                return this.cli_celularField;
            }
            set {
                this.cli_celularField = value;
                this.RaisePropertyChanged("cli_celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string cli_telefono {
            get {
                return this.cli_telefonoField;
            }
            set {
                this.cli_telefonoField = value;
                this.RaisePropertyChanged("cli_telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string cli_fecha_nacimien {
            get {
                return this.cli_fecha_nacimienField;
            }
            set {
                this.cli_fecha_nacimienField = value;
                this.RaisePropertyChanged("cli_fecha_nacimien");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int cli_tipo_identifi {
            get {
                return this.cli_tipo_identifiField;
            }
            set {
                this.cli_tipo_identifiField = value;
                this.RaisePropertyChanged("cli_tipo_identifi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int cli_sexo {
            get {
                return this.cli_sexoField;
            }
            set {
                this.cli_sexoField = value;
                this.RaisePropertyChanged("cli_sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("sessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string cokie {
            get {
                return this.cokieField;
            }
            set {
                this.cokieField = value;
                this.RaisePropertyChanged("cokie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string scriptSecurity {
            get {
                return this.scriptSecurityField;
            }
            set {
                this.scriptSecurityField = value;
                this.RaisePropertyChanged("scriptSecurity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int conveyanceID {
            get {
                return this.conveyanceIDField;
            }
            set {
                this.conveyanceIDField = value;
                this.RaisePropertyChanged("conveyanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int profesionID {
            get {
                return this.profesionIDField;
            }
            set {
                this.profesionIDField = value;
                this.RaisePropertyChanged("profesionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string university {
            get {
                return this.universityField;
            }
            set {
                this.universityField = value;
                this.RaisePropertyChanged("university");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int neighborhoodID {
            get {
                return this.neighborhoodIDField;
            }
            set {
                this.neighborhoodIDField = value;
                this.RaisePropertyChanged("neighborhoodID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int numberChildren {
            get {
                return this.numberChildrenField;
            }
            set {
                this.numberChildrenField = value;
                this.RaisePropertyChanged("numberChildren");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int stratumID {
            get {
                return this.stratumIDField;
            }
            set {
                this.stratumIDField = value;
                this.RaisePropertyChanged("stratumID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int epsID {
            get {
                return this.epsIDField;
            }
            set {
                this.epsIDField = value;
                this.RaisePropertyChanged("epsID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string rh {
            get {
                return this.rhField;
            }
            set {
                this.rhField = value;
                this.RaisePropertyChanged("rh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int prepaidHealth {
            get {
                return this.prepaidHealthField;
            }
            set {
                this.prepaidHealthField = value;
                this.RaisePropertyChanged("prepaidHealth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string contactPhone {
            get {
                return this.contactPhoneField;
            }
            set {
                this.contactPhoneField = value;
                this.RaisePropertyChanged("contactPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string contactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
                this.RaisePropertyChanged("contactName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int itrainingGoals {
            get {
                return this.itrainingGoalsField;
            }
            set {
                this.itrainingGoalsField = value;
                this.RaisePropertyChanged("itrainingGoals");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string ifirstTimeGym {
            get {
                return this.ifirstTimeGymField;
            }
            set {
                this.ifirstTimeGymField = value;
                this.RaisePropertyChanged("ifirstTimeGym");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<int> ihowKnow {
            get {
                return this.ihowKnowField;
            }
            set {
                this.ihowKnowField = value;
                this.RaisePropertyChanged("ihowKnow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<int> idPais {
            get {
                return this.idPaisField;
            }
            set {
                this.idPaisField = value;
                this.RaisePropertyChanged("idPais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string RUC {
            get {
                return this.rUCField;
            }
            set {
                this.rUCField = value;
                this.RaisePropertyChanged("RUC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validatefootprint", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class validatefootprintRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int cdgimnasio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string identifi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] imageBytes;
        
        public validatefootprintRequest() {
        }
        
        public validatefootprintRequest(int cdgimnasio, string identifi, byte[] imageBytes) {
            this.cdgimnasio = cdgimnasio;
            this.identifi = identifi;
            this.imageBytes = imageBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validatefootprintResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class validatefootprintResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string validatefootprintResult;
        
        public validatefootprintResponse() {
        }
        
        public validatefootprintResponse(string validatefootprintResult) {
            this.validatefootprintResult = validatefootprintResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Generic1SoapChannel : Sibo.Servicio.ListaBlanca.wsGSW.Generic1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Generic1SoapClient : System.ServiceModel.ClientBase<Sibo.Servicio.ListaBlanca.wsGSW.Generic1Soap>, Sibo.Servicio.ListaBlanca.wsGSW.Generic1Soap {
        
        public Generic1SoapClient() {
        }
        
        public Generic1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Generic1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Generic1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Generic1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public Sibo.Servicio.ListaBlanca.wsGSW.eTutorialVideo[] GetVideoTutorials(string formName, bool isNet, int applicationId) {
            return base.Channel.GetVideoTutorials(formName, isNet, applicationId);
        }
        
        public System.Threading.Tasks.Task<Sibo.Servicio.ListaBlanca.wsGSW.eTutorialVideo[]> GetVideoTutorialsAsync(string formName, bool isNet, int applicationId) {
            return base.Channel.GetVideoTutorialsAsync(formName, isNet, applicationId);
        }
        
        public Sibo.Servicio.ListaBlanca.wsGSW.eCliente[] getClientsFilterEmployed(string filter) {
            return base.Channel.getClientsFilterEmployed(filter);
        }
        
        public System.Threading.Tasks.Task<Sibo.Servicio.ListaBlanca.wsGSW.eCliente[]> getClientsFilterEmployedAsync(string filter) {
            return base.Channel.getClientsFilterEmployedAsync(filter);
        }
        
        public Sibo.Servicio.ListaBlanca.wsGSW.eHuellas[] GetHuella(int cdgimnasio, string clientID) {
            return base.Channel.GetHuella(cdgimnasio, clientID);
        }
        
        public System.Threading.Tasks.Task<Sibo.Servicio.ListaBlanca.wsGSW.eHuellas[]> GetHuellaAsync(int cdgimnasio, string clientID) {
            return base.Channel.GetHuellaAsync(cdgimnasio, clientID);
        }
        
        public Sibo.Servicio.ListaBlanca.wsGSW.eHuellas[] GetHuellaGym(int cdgimnasio) {
            return base.Channel.GetHuellaGym(cdgimnasio);
        }
        
        public System.Threading.Tasks.Task<Sibo.Servicio.ListaBlanca.wsGSW.eHuellas[]> GetHuellaGymAsync(int cdgimnasio) {
            return base.Channel.GetHuellaGymAsync(cdgimnasio);
        }
        
        public Sibo.Servicio.ListaBlanca.wsGSW.eHuellas[] GetHuellaGym2(int cdgimnasio) {
            return base.Channel.GetHuellaGym2(cdgimnasio);
        }
        
        public System.Threading.Tasks.Task<Sibo.Servicio.ListaBlanca.wsGSW.eHuellas[]> GetHuellaGym2Async(int cdgimnasio) {
            return base.Channel.GetHuellaGym2Async(cdgimnasio);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sibo.Servicio.ListaBlanca.wsGSW.validatefootprintResponse Sibo.Servicio.ListaBlanca.wsGSW.Generic1Soap.validatefootprint(Sibo.Servicio.ListaBlanca.wsGSW.validatefootprintRequest request) {
            return base.Channel.validatefootprint(request);
        }
        
        public string validatefootprint(int cdgimnasio, string identifi, byte[] imageBytes) {
            Sibo.Servicio.ListaBlanca.wsGSW.validatefootprintRequest inValue = new Sibo.Servicio.ListaBlanca.wsGSW.validatefootprintRequest();
            inValue.cdgimnasio = cdgimnasio;
            inValue.identifi = identifi;
            inValue.imageBytes = imageBytes;
            Sibo.Servicio.ListaBlanca.wsGSW.validatefootprintResponse retVal = ((Sibo.Servicio.ListaBlanca.wsGSW.Generic1Soap)(this)).validatefootprint(inValue);
            return retVal.validatefootprintResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sibo.Servicio.ListaBlanca.wsGSW.validatefootprintResponse> Sibo.Servicio.ListaBlanca.wsGSW.Generic1Soap.validatefootprintAsync(Sibo.Servicio.ListaBlanca.wsGSW.validatefootprintRequest request) {
            return base.Channel.validatefootprintAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sibo.Servicio.ListaBlanca.wsGSW.validatefootprintResponse> validatefootprintAsync(int cdgimnasio, string identifi, byte[] imageBytes) {
            Sibo.Servicio.ListaBlanca.wsGSW.validatefootprintRequest inValue = new Sibo.Servicio.ListaBlanca.wsGSW.validatefootprintRequest();
            inValue.cdgimnasio = cdgimnasio;
            inValue.identifi = identifi;
            inValue.imageBytes = imageBytes;
            return ((Sibo.Servicio.ListaBlanca.wsGSW.Generic1Soap)(this)).validatefootprintAsync(inValue);
        }
        
        public System.Data.DataTable ConsultadehuellasEntidad(int cdgimnasio, string identifi) {
            return base.Channel.ConsultadehuellasEntidad(cdgimnasio, identifi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ConsultadehuellasEntidadAsync(int cdgimnasio, string identifi) {
            return base.Channel.ConsultadehuellasEntidadAsync(cdgimnasio, identifi);
        }
        
        public bool getWithPaymentGateway() {
            return base.Channel.getWithPaymentGateway();
        }
        
        public System.Threading.Tasks.Task<bool> getWithPaymentGatewayAsync() {
            return base.Channel.getWithPaymentGatewayAsync();
        }
        
        public bool getWithDebitAccount() {
            return base.Channel.getWithDebitAccount();
        }
        
        public System.Threading.Tasks.Task<bool> getWithDebitAccountAsync() {
            return base.Channel.getWithDebitAccountAsync();
        }
        
        public bool getWithPaymentGatewayEmployed() {
            return base.Channel.getWithPaymentGatewayEmployed();
        }
        
        public System.Threading.Tasks.Task<bool> getWithPaymentGatewayEmployedAsync() {
            return base.Channel.getWithPaymentGatewayEmployedAsync();
        }
        
        public bool getWithDebitAccountEmployed() {
            return base.Channel.getWithDebitAccountEmployed();
        }
        
        public System.Threading.Tasks.Task<bool> getWithDebitAccountEmployedAsync() {
            return base.Channel.getWithDebitAccountEmployedAsync();
        }
        
        public string GetResultValidationsIncome(int cdgimnasio, int idsucursal, string clientID) {
            return base.Channel.GetResultValidationsIncome(cdgimnasio, idsucursal, clientID);
        }
        
        public System.Threading.Tasks.Task<string> GetResultValidationsIncomeAsync(int cdgimnasio, int idsucursal, string clientID) {
            return base.Channel.GetResultValidationsIncomeAsync(cdgimnasio, idsucursal, clientID);
        }
        
        public bool checkAutomaticDebit(int cdgimnasio, int idPlan, string idClient) {
            return base.Channel.checkAutomaticDebit(cdgimnasio, idPlan, idClient);
        }
        
        public System.Threading.Tasks.Task<bool> checkAutomaticDebitAsync(int cdgimnasio, int idPlan, string idClient) {
            return base.Channel.checkAutomaticDebitAsync(cdgimnasio, idPlan, idClient);
        }
        
        public string GetIdByQR(string qr, int cdgimnasio) {
            return base.Channel.GetIdByQR(qr, cdgimnasio);
        }
        
        public System.Threading.Tasks.Task<string> GetIdByQRAsync(string qr, int cdgimnasio) {
            return base.Channel.GetIdByQRAsync(qr, cdgimnasio);
        }
        
        public bool canceledForTemperature(string qr, int cdgimnasio, int branch, int temperature, string id, System.DateTime entryHour) {
            return base.Channel.canceledForTemperature(qr, cdgimnasio, branch, temperature, id, entryHour);
        }
        
        public System.Threading.Tasks.Task<bool> canceledForTemperatureAsync(string qr, int cdgimnasio, int branch, int temperature, string id, System.DateTime entryHour) {
            return base.Channel.canceledForTemperatureAsync(qr, cdgimnasio, branch, temperature, id, entryHour);
        }
        
        public string validationAccess(string qr, int cdgimnasio) {
            return base.Channel.validationAccess(qr, cdgimnasio);
        }
        
        public System.Threading.Tasks.Task<string> validationAccessAsync(string qr, int cdgimnasio) {
            return base.Channel.validationAccessAsync(qr, cdgimnasio);
        }
        
        public bool disableAccessCodes(int codigo, int cdgimnasio) {
            return base.Channel.disableAccessCodes(codigo, cdgimnasio);
        }
        
        public System.Threading.Tasks.Task<bool> disableAccessCodesAsync(int codigo, int cdgimnasio) {
            return base.Channel.disableAccessCodesAsync(codigo, cdgimnasio);
        }
    }
}
