//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicDocumentMovement
    {
        public int ElectronicDocumentMovementID { get; set; }
        public int GYMID { get; set; }
        public int ElectronicDocumentTypeID { get; set; }
        public int Identifier { get; set; }
        public Nullable<int> DianID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public int TechnologicalSupplierID { get; set; }
        public int ElectronicStateID { get; set; }
        public int ResponseCodeTechnologicalSupplierID { get; set; }
        public Nullable<bool> Modified { get; set; }
        public string bits_replica { get; set; }
        public string CreationUser { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Response { get; set; }
        public Nullable<int> intNumReintentos { get; set; }
        public string JSON_Enviado { get; set; }
        public string tipoDocumento { get; set; }
    }
}
