//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anthropometry
    {
        public int AnthropometryID { get; set; }
        public int InitialAge { get; set; }
        public int FinalAge { get; set; }
        public int Sex { get; set; }
        public double ConstantC { get; set; }
        public double ConstantM { get; set; }
    }
}
