//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEL_Lista_Bancos
    {
        public string lstb_CodigoBanco { get; set; }
        public string lstb_NombreBanco { get; set; }
        public System.DateTime lstb_FechaActualizacion { get; set; }
        public int cdgimnasio { get; set; }
    }
}
