//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_performFieldDetail
    {
        public int PK_performFieldDetailId { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<int> appointmentId { get; set; }
        public int FK_performFieldId { get; set; }
        public string value { get; set; }
        public string sectionName { get; set; }
        public string subsectionName { get; set; }
        public string client_idenitfi { get; set; }
        public Nullable<bool> isEdit { get; set; }
    
        public virtual gim_performFields gim_performFields { get; set; }
    }
}
