//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_cancela_recurrencia
    {
        public int gim_id_estado_recurrencia { get; set; }
        public string gim_identificacion_cliente { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<bool> cancellationState { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
