//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    
    public partial class spSignatureRegister_Result
    {
        public string strIdentificacionEmpleado { get; set; }
        public byte[] FirmaDigital { get; set; }
        public string strNumeroRegistro { get; set; }
    }
}
