//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Maestro_Localidades
    {
        public int id { get; set; }
        public string codigo_string { get; set; }
        public int cdgimnasio { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public Nullable<int> idCiudad { get; set; }
    }
}
