//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEL_CobroRecuDebito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEL_CobroRecuDebito()
        {
            this.PEL_CobroCuenta = new HashSet<PEL_CobroCuenta>();
        }
    
        public int crd_intId { get; set; }
        public string crd_strIdentificacion { get; set; }
        public int crd_intPlan { get; set; }
        public int crd_intSucursal { get; set; }
        public System.DateTime crd_FechaUltimoReintento { get; set; }
        public System.DateTime crd_FechaSiguientePago { get; set; }
        public int crd_cdgimnasio { get; set; }
        public int crd_intEstado { get; set; }
        public int crd_Reintentos { get; set; }
        public Nullable<bool> crd_activa { get; set; }
        public Nullable<bool> crd_cobropendiente { get; set; }
        public Nullable<int> crd_pla_inscripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEL_CobroCuenta> PEL_CobroCuenta { get; set; }
        public virtual TblEstado TblEstado { get; set; }
    }
}
