//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataCommerce
    {
        public int DataCommerceID { get; set; }
        public int PaymentMethodID { get; set; }
        public string Identifier { get; set; }
        public string TransactionalKey { get; set; }
        public int cdgimnasio { get; set; }
        public int BranchID { get; set; }
        public string MerchantID { get; set; }
        public string AccountID { get; set; }
        public double MaximumValue { get; set; }
        public string UserCreation { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string UserModify { get; set; }
        public Nullable<System.DateTime> DateModify { get; set; }
    }
}
