//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gim_planes_sucursal
    {
        public int plansuc_intpkPlan { get; set; }
        public int plansuc_intpkSucursal { get; set; }
        public Nullable<double> plansuc_floValor { get; set; }
        public Nullable<bool> plansuc_bitActiva { get; set; }
        public Nullable<bool> plansuc_bitPuedeIngresar { get; set; }
        public Nullable<int> plansuc_modificado { get; set; }
        public Nullable<bool> bool_modificado_replica { get; set; }
        public int cdgimnasio { get; set; }
        public Nullable<bool> plansuc_ventaonline { get; set; }
        public Nullable<bool> plansuc_ventanuevosclientes { get; set; }
        public string bits_replica { get; set; }
        public Nullable<bool> plansuc_ventaantiguos { get; set; }
        public string Zonas { get; set; }
    }
}
