//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.WhiteList.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistroEntrenamiento
    {
        public int intpkIdRegistroEnt { get; set; }
        public string strIdentificacionClienteReg { get; set; }
        public int cdGimnasio { get; set; }
        public int intfkRutina { get; set; }
        public int intFKEjercicio { get; set; }
        public int intNumeroSemana { get; set; }
        public int intDia { get; set; }
        public System.DateTime dtmFecha { get; set; }
        public int intTiempo { get; set; }
        public int intPeso { get; set; }
        public int intDistancia { get; set; }
        public int intRepeticiones { get; set; }
    }
}
